### ISSUE TITLE
Define "exposed to assistive technologies"

### ISSUE THREAD

**Issue by skotkjerra** [auto-wcag/auto-wcag#108]
(based on issue: https://github.com/auto-wcag/auto-wcag/issues/100)   
# Exposed to assistive technologies
Any element that is contained in the accessibility tree as described in [Core Accessibility API Mappings 1.1](https://www.w3.org/TR/core-aam-1.1/)

**Comment by annethyme** [comment]
Consider adding "... or is [focusable][]"

**Comment by kasperisager** [comment]
I'd suggest we limit our definition to the cases that __MUST NOT__ be exposed to AT, i.e.:

- `role="none"` or `role="presentation"
- Elements that don't generate layout boxes

**Comment by jkodu** [comment]
@kasperisager 

Are you happy that the PR https://github.com/auto-wcag/auto-wcag/pull/269 will cover this scenario?

**Comment by kasperisager** [comment]
@jkodu Yep 👌
