### ISSUE TITLE
Algorithm: Semantic role

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#114]
---
title: Semantic Role 
key: semantic-role
---

A semantic association that indicates an object's type. This allows tools to present and support interaction with the object in a manner  #that is consistent with user expectations about other objects of that type.

[Roles](https://www.w3.org/TR/wai-aria-1.1/#dfn-role) can be [implicit](https://www.w3.org/TR/wai-aria/#implicit_semantics) through the element type or explicit through the [role attribute](https://www.w3.org/TR/html/dom.html#aria-role-attribute). 

**Note**: For HTML elements the implicit roles are documented in [ARIA in HTML](https://www.w3.org/TR/html-aria/).

**Comment by annethyme** [comment]
First draft for definition comes from issue https://github.com/auto-wcag/auto-wcag/issues/105.

Definition has been tightened up and links updated to normative sources.

**Comment by Brynanders** [comment]
Could we simplify this to say something like

> [Using WAI-ARIA][https://www.w3.org/TR/wai-aria-1.1/#usage_intro] Roles to expose the intended semantic purpose of the HTML elements they are assigned to.

**Comment by WilcoFiers** [comment]
Closing as there is a PR open ATM
