### ISSUE TITLE
On hold: Define "distinguishing border"

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#128]
(from draft: https://github.com/auto-wcag/auto-wcag/blob/master/_drafts/SC1-4-1-link-style-in-text.md)

## Distinguishing Border

Look at the width, style, and color of the border-top, border-bottom or outline.

For one of these to be a distinguishing border, all the following must be true:

* The *-width is greater than 0
* The *-style is not set to none 
* The *-color is not transparent

If either border-top, border-bottom or outline is distinguishable, the element has a distinguishing border.

### Assumptions
* Use of a border, of 1 or more pixels, not set to none, and not with a color of transparent, is assumed to be sufficiently distinguishable.

**Comment by kasperisager** [comment]
Should be accept use of box shadows in place of borders?

**Comment by annethyme** [comment]
Take box shadow into consideration when writing this definition.

**Comment by WilcoFiers** [comment]
I disagree. My and @jkodu have been playing around with border contrast. I think for the sake of simplicity, we should not try to combine too many things. If we want to add box shadows as a distinguishing style for links, we're better off with a separate definition.

**Comment by kasperisager** [comment]
I completely agree on having a separate definition for this as it's entirely possible that we would want to distinguish between the two, e.g. requiring only one and disregarding the other.

**Comment by annethyme** [comment]
Definition included in issue for rule: https://github.com/auto-wcag/auto-wcag/issues/92
