### ISSUE TITLE
Define "rendered text content"

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#131]
(Needed for #92)

## Rendered text content
[Non-empty][] [text content][] that is [visible on the page][].

[non-empty]: ../pages/algorithms/non-empty.html
[text content]: ../pages/algorithms/text-content.html
[visible on the page]: ../pages/algorithms/visible-on-page.html

**Comment by WilcoFiers** [comment]
@annethyme Changing this algorithm changes the meaning of existing rules. Please have a look if those actually need to be changed. I suspect you may need to create a different term for "visible text". This stems from this difficulty that there are different ways something can be "hidden".

**Comment by kasperisager** [comment]
@WilcoFiers We will have to revisit our definition of the term "rendered" as it's currently not aligned with the HTML specification: https://www.w3.org/TR/html/rendering.html#being-rendered.

**Comment by annethyme** [comment]
See how much can be covered by https://github.com/auto-wcag/auto-wcag/pull/278

**Comment by annethyme** [comment]
This similar definition has made it to published state: https://auto-wcag.github.io/auto-wcag/pages/glossary/visible-text-content.html
