### ISSUE TITLE
audio or video avoids automatically playing audio (80f0bf): atomic rule named incorrectly in exectation section

### ISSUE THREAD

**Issue by adilsofficial** [auto-wcag/auto-wcag#1427]
The atomic rule _"Audio or video that plays automatically has no audio that lasts more than 3 seconds ([aaa1bf](https://act-rules.github.io/rules/aaa1bf))"_ named incorrectly in _Expextation_ section of the rule [80f0bf](https://act-rules.github.io/rules/80f0bf#expectation). However relevant atomic rules are listed corrected in _Input Rules_ section of the rule.

**Comment by WilcoFiers** [comment]
I've opened a PR to fix this. Thanks for reporting Adil!
