### ISSUE TITLE
Define "visible text content"

### ISSUE THREAD

**Issue by Brynanders** [auto-wcag/auto-wcag#143]
---
title: visible text content
---
Note: If its not content we don't care about

**Comment by annethyme** [comment]
There are other ways to visually hide text content than non-text content, e.g.: 

- color is transparent
- font-size: 0
- text-indent that pushes the text outside of its visible box
- color contrast: 0

Therefore we feel that a "visible text content" algorithm is needed, in addition to a "visible non-text content" algorithm.
If the text content is contained within a parent that is not visible non-text content, then the text is not visible.

**Comment by annethyme** [comment]
Replaced by https://github.com/auto-wcag/auto-wcag/pull/278
