### ISSUE TITLE
Algorithm: Document context

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#154]

**Comment by annethyme** [comment]
From conversation on https://github.com/auto-wcag/auto-wcag/pull/134: 

@WilcoFiers: 

> We should add a note here explaining "document context". Something like:
> note: Elements can live in different document contexts if they are part of different shadow DOM trees. Elements not inside shadow DOM are always on the same document context.

@kasperisager 

> I'd suggest we rely on the concept of a root node in defining document contexts: https://dom.spec.whatwg.org/#dom-node-getrootnode

**Comment by jkodu** [comment]
PR #225
