### ISSUE TITLE
Define "Heading"

### ISSUE THREAD

**Issue by DagfinnRomen** [auto-wcag/auto-wcag#156]
(needed for  #70)

## Heading

Headings are identified by visual clues such as bolder text, the text being italic, or larger font-size and visually appears as a head for a section of content.

Headings are used to organise the content and relates to the following section of content on the web page.

**Comment by WilcoFiers** [comment]
I fundamentally disagree with defining headings by its visual characteristics. Pulling up a random definition of a heading:

> A heading is a word, phrase, or sentence at the beginning of a written passage that explains what it's about. A heading is very similar to a title. A heading is similar to a caption, a line below a photograph that briefly explains it.

What is or isn't a heading isn't influenced by its style. Plain text documents don't support styling text, by that logic, those documents wouldn't have headings. A heading, if we need a definition at all, should be defined by its purpose in the text.

Either way you do this, you've got an open ended definition, which means it shouldn't be used as part of the applicability section. This kind of "I know it when I see it" definitions aren't allowed in ACT RF in applicability.

**Comment by annethyme** [comment]
Maybe we could ude this (in-progress) definition of "disinguishing style" (https://github.com/auto-wcag/auto-wcag/issues/127) for https://github.com/auto-wcag/auto-wcag/issues/70 somehow? 
The definition for "distinguishing style" really needs tightening up still, though. 

Then maybe the title for this "Heading" definiton could be something like "visual heading" instead, and the definition could build on the "distinguishing style" definition + some extra, heading-related stuff...

**Comment by annethyme** [comment]
I am going to close this because it is no longer necessary for the rule that it was originally intended for, https://auto-wcag.github.io/auto-wcag/rules/SC2-4-6-descriptive-headings.html.

If we pick up a rule for visual headings, this glossary term could be relevant again, though.
