### ISSUE TITLE
Split out sections for Applicability test cases and Expectations test cases?

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#160]
For ACT rule writers without a development background knowing how to write test cases can difficult, and questions like "How do I know if when I have written enough test cases?", "Do I really need this many test cases?" and "Should this be one or two different test cases?" are just some of the questions that I have heard recently when working with different Auto-WCAG members on rules writing.

To address this internally, we at Siteimprove had a work shop on rule writing, where our auto-wcag members with an accessibility background learned about black-box testing and the equivalence partitioning test case design technique. Based on this workshop, I have the following suggestion:

I suggest that we split up the test cases for rules into:

- test cases for Applicability (Applicable + Inapplicable), and 
- test cases for Expectations (Passed + Failed) 

By doing this I believe we can better:

- guide rule writers in creating test cases
- help rule reviewers in deciding if the test case coverage is good enough, and 
- help implementers in determining if their rule implementation is valid.

Suggestion for changes to rule template to address this (which should probably also be followed by some guidelines + guidance in one of our supporting documents): 

#### Applicable 

**Note:** When running the rule on the Applicable test cases, the outcome should be either a pass or a fail

```html
Code snippet to demonstrate any applicable test cases. Make sure to create test cases that represents all the different ways an item can be applicable, with only one way represented per test case.
```

#### Inapplicable 

```html
Code snippet to demonstrate any inapplicable test cases. Make sure to create test cases that represents all the different ways an item can be inapplicable, with only one way represented per test case.
```

### Expectations test cases

_If possible, choose one of the test cases from the "Applicable" test case set and modify that one to go through all of the possible Passed/Failed scenarios._

### Passed

```html
Code snippet to demonstrate any passed test cases. Make sure to create test cases that represents all the different ways an item can pass the expectations, with only one way represented per test case.
```

#### Failed

```html
Code snippet to demonstrate any failed test cases. Make sure to create test cases that represents all the different ways an item can fail the expectations, with only one way represented per test case.
```

**Comment by EmmaJP** [comment]
In regard test cases ... would it be worth requiring that at least one person involved with a set of test cases (creator or one of the reviewers) has some development background. Especially if the test cases included code, which I suspect most will.

**Comment by WilcoFiers** [comment]
Agreed not to move forward on this with Anne.
