### ISSUE TITLE
Chore: Include comments for test cases in rule template

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#161]
One thing that I have found extremely helpful in ensuring the quality of the test cases for a rule and the ability to have others review them, is adding notes in the html snippet. 

I suggest we include this as a default in the template, to ensure that as many as possible benefit from this possibility:

### Passed

```html
<!-- Note explaining why this test case is included here -->
Code snippet to demonstrate any passed test cases.
```

### Failed

```html
<!-- Note explaining why this test case is included here -->
Code snippet to demonstrate any passed test cases.
```

etc.

**Comment by jkodu** [comment]
This has been tackled now. Code in master already reflects this. Hence closing.
