### ISSUE TITLE
Chore: Simplify Auto-WCAG workflow

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#162]
A few months into dedicated Auto-WCAG rule writing it has become apparent to me that ACT rule writing is a very circular process, which is not easily illustrated by/mapped to our current workflow, where the draft/final split gives the idea that there is a clear flow forward through the process.
 
@jkodu, @Brynanders and I tried to illustrate the current process when making a brand new Kanban board for the Auto-WCAG group: https://github.com/auto-wcag/auto-wcag/projects/1.

The current stages, as seen by us when creating the visualisation for the board, are something like this: 
- **Issue**
- **Draft** (3 approvals - process is to just comment and approve. In practice, comments are often forgotten and have to be repeated later on the new "final" pull request)
- (new "final" pull request instead of the "draft" pull request)
- **Changes requested** 
- **Final** (3 approvals OR change requests) (often circulated back many, many times)
- **Auto-WCAG approval**
- **Final**

The draft/final split seems a bit artificial to me, since things usually move very fast from the draft stage to the final one, where it is then looping back and forth forever. 

I talked this over with @kasperisager, and I propose simplifying the workflow to just have one "in progress"/"draft" stage and one " peer review" stage, since things will circle back and forth in an iterative process anyway. Suggestion for a new workflow: 

- **Idea / Issue** (maybe take it up in the Auto-WCAG group already here to find out if this is a rule we want to do at all?)
- **In progress / Draft** (by requesting reviews, rule moves to next stage)
- **Peer review** (3 approvals) (if changes are requested, draft goes back to In progress)
- **Review by the Auto-WCAG group** 
- **Rule**

I can see why we earlier on would have wanted to have a folder of draft rules, to visualize things that are being worked on, but I think this role is better covered by the Kanban board, now that we have that possibility. Then there will always be a link to the most recent draft of a rule, instead of having a draft folder of potentially outdated rules, because they are being developed even further, on their way to becoming final rules.

**Comment by annethyme** [comment]
New project board was created on July 9, 2018, that in my opinion satisfies the needs described here. 
See new project board: https://github.com/auto-wcag/auto-wcag/projects/4
It uses an automated worflow, and has the following states: 

- To Do
- In Progress
- Needs Review
- Reviewer Approved 
- Done

**Comment by annethyme** [comment]
Closing this issue, since a new workflow is in place.
Opened new issues for the documentation part: https://github.com/auto-wcag/auto-wcag/issues/178

**Comment by kasperisager** [comment]
I dig it 🙌
