### ISSUE TITLE
Chore: Update test cases format (PR #230)

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#177]
The existing format is missing some stuff, namely an easy way to identify the test case, and a description. I would like to solve that by using the following structure:

````md
## Test cases

### Passes

#### Pass 1 {#pass-1}

Some description

```html
My html
```
````

**Comment by jkodu** [comment]
@WilcoFiers - Is there an agreement on this yet?

**Comment by jkodu** [comment]
Looks like we are writing all new rules in this format, some housekeeping has top be done for the already published ones. I will do that.

**Comment by jkodu** [comment]
PR #230 merged. Closing issue.
