### ISSUE TITLE
Media rules: The plan

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#180]
In creating media rules we found ourselves stumbling over the complexities of dealing with very similar requirements over multiple SCs. We've come up with the following solution, using composed / atomic rules.

D! = Duplicated across several composed rules.

### SC1-2-1-video-only (#276)
  - SC1-2-1-media-alternative-video (DONE but edited in #276)
  - SC1-2-1-video-only-element-transcript (#276)
  - SC1-2-1-video-only-description-track (#276)
  - SC1-2-1-video-only-audio-alternative (#276)

### SC1-2-1-audio-only (#276)
  - SC1-2-1-audio-transcript (#276)
  - SC1-2-1-media-alternative-audio (DONE but edited in #276)

### SC1-2-2-video-has-audio-alternative (DONE #158)
  - SC1-2-2-video-has-captions (DONE #158)
  - SC1-2-video-media-alternative (#204) (D!)

### SC1-2-3-video-alternative (#204)
  - SC1-2-video-transcript (DONE in #106 and later edited in #157) (D!)
  - SC1-2-video-audio-description (#204) (D!)
  - SC1-2-video-media-alternative (#204) (D!)
  - SC1-2-video-description-track (DONE in #106 and later edited in #157) (D!)

### SC1-2-5-video-description (#204)
  - SC1-2-video-audio-description (#204) (D!)
  - SC1-2-video-media-alternative (#204) (D!)
  - SC1-2-video-description-track (DONE in #106 and later edited in #157) (D!)

### 1.2.8 (Level AAA)
- SC1-2-video-transcript (DONE in #106 and later edited in #157) (D!)

**Comment by WilcoFiers** [comment]
Rules (no duplicates)

- SC1-2-1-media-alternative-audio (DONE)
- SC1-2-1-media-alternative-video (DONE)
- SC1-2-video-transcript (DONE)
- SC1-2-video-description-track (DONE)
- SC1-2-1-video-only (#276)
- SC1-2-1-audio-only (#276)
- SC1-2-2-audio-captions (updated and renamed into 
- SC1-2-1-audio-tran- script in #276)
- SC1-2-1-audio-tran- script (#276)
- SC1-2-1-video-only-description-track (video only) (#276)
- SC1-2-2-video-has-audio-alternative (#158)
- SC1-2-2-video-has-captions (#158)
- SC1-2-video-media-alternative (#204)
- SC1-2-3-video-alternative (#204)
- SC1-2-video-audio-description (#204)
- SC1-2-video-media-alternative (#204)
- SC1-2-5-video-description (#204)

**Comment by annethyme** [comment]
These three on Wilco's "Rules (no duplicates)" list seems to be the same: 
* SC1-2-2-audio-captions (updated and renamed into
* SC1-2-1-audio-tran- script in #276)
* SC1-2-1-audio-tran- script (#276)

And there also seems to be two of these: 
- SC1-2-video-media-alternative (#204)
- SC1-2-video-media-alternative (#204)

And it seems that the list is missing this rule (or these rules?) from the first comment in this thread from Wilcos' "Rules (no duplicates)" list? 
* SC1-2-1-video-or-audio-only (#276) (should probably be split into 2)

This would make 15 rules altogether, which is the count I have heard before.

@Wilco, can you help sort this out?

**Comment by annethyme** [comment]
@WilcoFiers and @ShadowBB, can we close this one now?
