### ISSUE TITLE
"Image button has non-empty accessible name" [59796f]: HTML spec require `alt` on image button, making several examples fail 4.1.1

### ISSUE THREAD

**Issue by Jym77** [auto-wcag/auto-wcag#1895]
So, today I learnt that [`alt` is mandatory on image buttons](https://html.spec.whatwg.org/multipage/input.html#attr-input-alt) (https://github.com/act-rules/act-rules.github.io/issues/1893#issuecomment-1189309086)

In [Image button has non-empty accessible name](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/), we have several test cases with image buttons without an `alt` attribute ([Passed Example 2](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#passed-example-2), [Passed Example 3](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#passed-example-3), [Passed Example 4](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#passed-example-4), [Failed Example 1](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#failed-example-1), and [Failed Example 3](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#failed-example-3)).

This means that these examples fail 4.1.1. Which goes against our test case design guidelines, notably:
* [Test cases](https://act-rules.github.io/pages/design/rule-design/#test-cases): "All examples should demonstrate good practice, with allowances for omitting code not directly relevant for the rule, so as to be succinct." <= I'm not sure the lack of `alt` on the Passed Examples fits in the "omitting code not directly relevant for the rule" exception.
* Testers may report a 4.1.1 error on these cases which makes the implementation inconsistent because it flags too much.

The easiest way to fix all cases is to add an empty `alt` attribute (plus a note explaining why), but that is not exactly good practice. Maybe adding `alt="Submit Button"` everywhere is slightly better but still not ideal (HTML spec: "The `alt` attribute (…) must contain a non-empty string giving the label that would be appropriate for an equivalent button if the image was unavailable.", so non-descriptive `alt` is actually bad and the rule assumes that "Submit Button" is not descriptive…)

**Comment by Jym77** [comment]
Plot twist, it seems that [`alt` is also mandatory on `img`](https://html.spec.whatwg.org/multipage/images.html#alt):
> Except where otherwise specified, the [alt](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-alt) attribute must be specified and its value must not be empty; the value must be an appropriate replacement for the image.

🤔 

---
Note that 
* `<input type="image" aria-label="foo" />` fails [validator](https://validator.w3.org/) with error "Error: Element `input` is missing required attribute `alt`."
* `<img src="foo.jpg" aria-label="foo" />` fails it with two errors "Error: An `img` element with no `alt` attribute must not have any `aria-*` attributes other than `aria-hidden`." and "Error: An `img` element must have an `alt` attribute, except under certain conditions."

So it seems both of these fail 4.1.1 (and that for `img` elements it would be hard to fail 1.1.1 without also failing 4.1.1).

**Comment by giacomo-petri** [comment]
> The easiest way to fix all cases is to add an empty alt attribute (plus a note explaining why), but that is not exactly good practice. 

I agree

> Maybe adding alt="Submit Button" everywhere is slightly better but still not ideal (HTML spec: "The alt attribute (…) must contain a non-empty string giving the label that would be appropriate for an equivalent button if the image was unavailable.", so non-descriptive alt is actually bad and the rule assumes that "Submit Button" is not descriptive…)

This will also impact [Passed Example 4](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#passed-example-4), resulting in a different accessible name given by the alt attribute (and not the title attribute).

> Note that
> 
> - `<input type="image" aria-label="foo" />` fails [validator](https://validator.w3.org/) with error "Error: Element input is missing required attribute alt."
> - `<img src="foo.jpg" aria-label="foo" />` fails it with two errors "Error: An img element with no alt attribute must not have any aria-* attributes other than aria-hidden." and "Error: An img element must have an alt attribute, except under certain conditions."

Similarly, also `<img src="decorative-bg.jpg" role="presentation/none">` fails validator with errors:
- An img element with no alt attribute must not have a role attribute.
- Error: An img element must have an alt attribute, except under certain conditions. For details, consult [guidance on providing text alternatives for images](https://www.w3.org/WAI/tutorials/images/).

On the other hand, in [guidance on providing text alternatives for images](https://www.w3.org/WAI/tutorials/images/), [decorative images](https://www.w3.org/WAI/tutorials/images/decorative/), Example 1: Image used as part of page design, it seems a valid solution.

As emerged from [#1893](https://github.com/act-rules/act-rules.github.io/issues/1893), or at least how I've interpreted the 4.1.1 criterion, a parsing issue is not always an accessibility issue, and consequently, it might not be a 4.1.1 failure. We all agree that having a robust code that passes the validator is always a best practice, but might not be always needed in terms of WCAG if it doesn't impact accessibility.
In fact, per 4th sufficient technique of [4.1.1 Parsing SC](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html)

> - [H74: Ensuring that opening and closing tags are used according to specification](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H74) (HTML)
> - AND [H93: Ensuring that id attributes are unique on a Web page](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H93) (HTML)
> - AND [H94: Ensuring that elements do not contain duplicate attributes](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H94) (HTML)

I assume that the alt attribute is mandatory in terms of parsing, but if the element is properly managed, might not be a 4.1.1 failure.

Is that acceptable?

----

That said, what if we clearly specify that, for the purpose of the rule, we've consciously removed the alt attribute?

**Comment by giacomo-petri** [comment]
> This means that these examples fail 4.1.1. Which goes against our test case design guidelines, notably:

@Jym77, based on https://github.com/w3c/wcag/issues/2525#issue-1280898890, they do not fail 4.1.1.

> [Test cases](https://act-rules.github.io/pages/design/rule-design/#test-cases): "All examples should demonstrate good practice, with allowances for omitting code not directly relevant for the rule, so as to be succinct." <= I'm not sure the lack of alt on the Passed Examples fits in the "omitting code not directly relevant for the rule" exception.

I'm not sure if the lack of alt attribute, in particular circumstances such as having an aria-label(ledby), can still be considered a bad practice. Maybe is not the best one, as having the alt attribute represents a standard (and a parsing validator requirement), but in terms of accessibility doesn't affect users experience.

**Comment by Jym77** [comment]
Reading https://github.com/w3c/wcag/issues/2525, I agree these are not 4.1.1 problems. Closing this.
