### ISSUE TITLE
bc4a75: Pass example 6 no longer passing in ARIA 1.2

### ISSUE THREAD

**Issue by tombrunet** [auto-wcag/auto-wcag#1900]
https://act-rules.github.io/rules/bc4a75

Pass example 6:
```
<div role="list">
	<span role="listitem">Item 1</span>
	<div role="group">
		<span role="listitem">Item 2</span>
		<span role="listitem">Item 3</span>
	</div>
</div>
```

ARIA 1.1 allows a group child for `list`: https://www.w3.org/TR/wai-aria-1.1/#list
ARIA 1.2 DOES NOT allow a group child: https://www.w3.org/TR/wai-aria-1.2/#list

**Comment by tombrunet** [comment]
Should Pass 6 be removed? Or should it be changed to other roles?

**Comment by WilcoFiers** [comment]
Looking into this. Not sure if we need this to become a failed example... TBH. This is the PR where it's changed in ARIA:
https://github.com/w3c/aria/pull/1053

**Comment by carlosapaduarte** [comment]
Updated in #1940
