### ISSUE TITLE
Autocomplete attribute has valid value - Input type image [73f2c2]

### ISSUE THREAD

**Issue by giacomo-petri** [auto-wcag/auto-wcag#1901]
- Rule: Autocomplete attribute has valid value
- URL: https://www.w3.org/WAI/standards-guidelines/act/rules/73f2c2/#attribute-value
- Reference: https://html.spec.whatwg.org/#image-button-state-(type=image)    

    > The following content attributes must not be specified and [do not apply](https://html.spec.whatwg.org/#do-not-apply) to the element: [accept](https://html.spec.whatwg.org/#attr-input-accept), [autocomplete](https://html.spec.whatwg.org/#attr-fe-autocomplete), [checked](https://html.spec.whatwg.org/#attr-input-checked), [dirname](https://html.spec.whatwg.org/#attr-fe-dirname), [list](https://html.spec.whatwg.org/#attr-input-list), [max](https://html.spec.whatwg.org/#attr-input-max), [maxlength](https://html.spec.whatwg.org/#attr-input-maxlength), [min](https://html.spec.whatwg.org/#attr-input-min), [minlength](https://html.spec.whatwg.org/#attr-input-minlength), [multiple](https://html.spec.whatwg.org/#attr-input-multiple), [pattern](https://html.spec.whatwg.org/#attr-input-pattern), [placeholder](https://html.spec.whatwg.org/#attr-input-placeholder), [readonly](https://html.spec.whatwg.org/#attr-input-readonly), [required](https://html.spec.whatwg.org/#attr-input-required), [size](https://html.spec.whatwg.org/#attr-input-size), and [step](https://html.spec.whatwg.org/#attr-input-step).

- Description:

    in _**Applicability**_ section (exception)

    > - fixed value: the element is an input element with a type [attribute value](https://www.w3.org/WAI/standards-guidelines/act/rules/73f2c2/#attribute-value) of hidden, button, submit or reset; or

    Should we add also _image_ in the type list?

    In addition, also the _file_ type does not accept the autocomplete attribute (https://html.spec.whatwg.org/#file-upload-state-(type=file))
    
    > The following content attributes must not be specified and [do not apply](https://html.spec.whatwg.org/#do-not-apply) to the element: [alt](https://html.spec.whatwg.org/#attr-input-alt), [autocomplete](https://html.spec.whatwg.org/#attr-fe-autocomplete), [checked](https://html.spec.whatwg.org/#attr-input-checked), [dirname](https://html.spec.whatwg.org/#attr-fe-dirname), [formaction](https://html.spec.whatwg.org/#attr-fs-formaction), [formenctype](https://html.spec.whatwg.org/#attr-fs-formenctype), [formmethod](https://html.spec.whatwg.org/#attr-fs-formmethod), [formnovalidate](https://html.spec.whatwg.org/#attr-fs-formnovalidate), [formtarget](https://html.spec.whatwg.org/#attr-fs-formtarget), [height](https://html.spec.whatwg.org/#attr-dim-height), [list](https://html.spec.whatwg.org/#attr-input-list), [max](https://html.spec.whatwg.org/#attr-input-max), [maxlength](https://html.spec.whatwg.org/#attr-input-maxlength), [min](https://html.spec.whatwg.org/#attr-input-min), [minlength](https://html.spec.whatwg.org/#attr-input-minlength), [pattern](https://html.spec.whatwg.org/#attr-input-pattern), [placeholder](https://html.spec.whatwg.org/#attr-input-placeholder), [readonly](https://html.spec.whatwg.org/#attr-input-readonly), [size](https://html.spec.whatwg.org/#attr-input-size), [src](https://html.spec.whatwg.org/#attr-input-src), [step](https://html.spec.whatwg.org/#attr-input-step), and [width](https://html.spec.whatwg.org/#attr-dim-width).

**Comment by giacomo-petri** [comment]
\+ the autocomplete attribute does not apply also to input type checkbox and radio.

**Comment by Jym77** [comment]
Yes, good catch.
Can you check all the possible `input` types and update the rule to list all the ones where `autocomplete` does not apply (+ keep `hidden` where it applies but with a different mantle…)?

It's probably worth to also add a Background note to explain this **fixed value** exception since it looks like this will be half of the input types 🤔
