### ISSUE TITLE
Image no text rule should not use "essential" in it expectation [0va7u6]

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#1915]
https://wai-wcag-act-rules.netlify.app/standards-guidelines/act/rules/0va7u6/proposed/

The first bullet of the exception reads:

> essential: the [visible pixels](https://wai-wcag-act-rules.netlify.app/standards-guidelines/act/rules/0va7u6/proposed/#visible) of the test target contain text for which its presentation is [essential](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html#dfn-essential); or

I think this is a problem. The definition of Essential from WCAG is fairly ambiguous I believe. I therefor don't think we're allowed to use it in the expectation. This seems to be the only rule for that currently uses it. Other rules that use it all have this in its assumption, where this restriction does not apply.

One possible solution could be to create a new definition that explicitly lists all known cases of when images of text are "essential". Maybe call it "essential images of text" or something. That leaves far less room for interpretation.

**Comment by carlosapaduarte** [comment]
From the CG discussion:
- this needs to be fixed to get approval from TF
- we'll try to create a list of know cases of essential images of text

**Comment by carlosapaduarte** [comment]
Similar approach in a different rule is going on on #1916
