### ISSUE TITLE
Can emails be "web pages (HTML)"?

### ISSUE THREAD

**Issue by Jym77** [auto-wcag/auto-wcag#1924]
We have a definition of [web pages (HTML)](https://act-rules.github.io/glossary/#web-page-html) stating:
> An HTML [web page](https://www.w3.org/TR/WCAG21/#dfn-web-page-s) is the set of all [fully active](https://html.spec.whatwg.org/#fully-active) [documents](https://dom.spec.whatwg.org/#concept-document) which share the same [top-level browsing context](https://html.spec.whatwg.org/#top-level-browsing-context).

I do feel this would include emails written as HTML, where the content is a document.

---
The problem? [the specs](https://html.spec.whatwg.org/multipage/semantics.html#the-head-element) have this wonderful note:
> The [title](https://html.spec.whatwg.org/multipage/semantics.html#the-title-element) element is a required child in most situations, but when a higher-level protocol provides [title](https://html.spec.whatwg.org/multipage/semantics.html#the-title-element) information, e.g., in the subject line of an email when HTML is used as an email authoring format, the title element can be omitted.

and I would agree that a document inside an email has its title provided by the message's subject and thus does not require a `title` element to satisfy 2.4.2… But the current rule would fail it…

---
Fortunately, that should be fairly easy to fix. The language rules have an assumption in the line of "`lang` is used, not a `content-language` HTTP header". We can similarly add an assumption to the title rules in the line of "`title` is used, not email subject".

**Comment by giacomo-petri** [comment]
Interesting topic and I agree with above.

At the same time, and I know it is not an author responsibility, but the recipient can forward the email to someone else changing the subject for some reason; and thus the title might not reflect the HTML email content.

The <title> tag will keep and ensure a meaningful description to the email content.

On the other hand, you might also edit the HTML but this will result in a different HTML source.

**Comment by Jym77** [comment]
> At the same time, and I know it is not an author responsibility, but the recipient can forward the email to someone else changing the subject for some reason; and thus the title might not reflect the HTML email content.

Absolutely. Or the original author might use a non-descriptive subject and the email still fails 2.4.2.

But ACT rules need to maintain the fail-on-fail relationship, and an HTML email without `<title>` element does not necessarily fails 2.4.2, so we need to take care of that.
