### ISSUE TITLE
Headers attribute rule should skip non-table roles [a25f45]

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#1928]
The following example would fail the [headers attribute rule](https://www.w3.org/WAI/standards-guidelines/act/rules/a25f45/), because the applicability only excludes table that are not in the accessibility tree. I think the exception should be broader, and exclude tables that do not have role=table, grid, or treegrid.

```html
<table role="region">
  <td id="self" headers="self">World</td>
</table>
```

**Comment by Jym77** [comment]
Another possibility could be to be inapplicable when there is no `th` element in the table (or no role of `*header`).

**Comment by giacomo-petri** [comment]
Considering the need to record accessibility support data, once we have agreed on that, might be worth to mention that with Safari (+ VO) semantic tables (managed using HTML 5 tags such as `<table>, <thead>, <tbody>, <tr>, <th>, <td>`, ...) styled using CSS properties such as display:flex do not behave as tables and, consequently, header cells neither. They are rendered as text nodes and role="..." attribute must be set to allow AT rendering them accordingly.

**Comment by carlosapaduarte** [comment]
Discussed in CG call: update applicability to exclude tables that do not have role table, grid, or treegrid

**Comment by giacomo-petri** [comment]
Hello group,

as per CG call, I'm providing table and list examples where, in Safari (and this is here for over a year - at least), CSS overrides the semantic of `<table>` and `<list>` elements.
Unfortunately (or fortunately :D) I'm no longer able to replicate the Chrome scenario I mentioned during the discussion (but it was replicable on November 4th).

- Standard table element with no CSS property set by the author - `<tr>` properly computed into the accessibility tree as a row:
    <img width="1792" alt="tr in standard table properly rendered as a row" src="https://user-images.githubusercontent.com/106394951/201186984-0f6058b6-78a9-4507-806a-b11a7c5f12d2.png">

- Table element with display:flex CSS property set - `<tr>` improperly computed into the accessibility tree as a text element (no matching ARIA role) - table content is announced as simple text:
    <img width="1792" alt="tr in flex table rendered as simple text" src="https://user-images.githubusercontent.com/106394951/201187564-36e79a71-9815-4fc1-82b1-84e0d3974270.png">

- Table element with display:flex CSS property set but also role="table" - `<tr>` properly computed into the accessibility tree as a row:
    <img width="1792" alt="tr in flex table but with role table rendered as a row" src="https://user-images.githubusercontent.com/106394951/201187793-9b2c4499-91a7-43c5-8e35-fd50ace3d336.png">

Similarly, list elements (`<ul>` or `<ol>`) with list-style-type:none CSS property are not recognized as list elements by Safari:

- Standard list element with no CSS property set by the author - `<ul>` properly computed into the accessibility tree as a list:
    <img width="1792" alt="standard list without CSS set by the author properly rendered" src="https://user-images.githubusercontent.com/106394951/201188974-4b502abc-dfcb-47bb-adbb-95becd5b9621.png">

- List element with list-style-type:none CSS property - `<ul>` improperly computed into the accessibility tree as a text element (no matching ARIA role) - list items are announced as simple text:
    <img width="1792" alt="list items in list with list style type none are rendered as simple text" src="https://user-images.githubusercontent.com/106394951/201189741-c7c943fa-d594-4230-8b91-5d5b25427026.png">

- List element with list-style-type:none CSS property set but also role="list" - `<ul>` properly computed into the accessibility tree as a list:
    <img width="1792" alt="list with list style none but also role list properly rendered as a list" src="https://user-images.githubusercontent.com/106394951/201189955-9d514acb-2fec-45c1-bba1-ee4072ce6af5.png">

Attached also the .zip with the examples for your own tests:
[example.html.zip](https://github.com/act-rules/act-rules.github.io/files/9984117/example.html.zip)


Giacomo

**Comment by giacomo-petri** [comment]
\+ If in Chrome you replace "display: flex" in the 2nd table with "display: contents" you obtain something similar to the scenario I was able to replicate on Nov 4th (but I'm pretty sure it was "display: flex" and for sure not "display: contents").
