### ISSUE TITLE
New Rule(s): Images must not have generic accessible names

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#195]
---
name: Images must not have generic accessible names
description: |
	This rule checks that images in a document have meaningful and discernible text alternatives.

success_criterion:
- 1.1.1 # Non-text Content

atomic_rules:
- [Image accessible name is unique](https://github.com/auto-wcag/auto-wcag/issues/215)
- [Image accessible name is not image file name](https://github.com/auto-wcag/auto-wcag/issues/216)
- [Image accessible name does not contain non-text content](https://github.com/auto-wcag/auto-wcag/issues/217)
- Valid use of generic accessible name for image [manual]

authors:
- Bryn Anderson
---

### Applicability

The rule applies to any HTML or SVG element with the semantic role of `img` that is exposed to assistive technologies. 

### Expectation

For each test target, the outcome of at least one of the following rules is passed:
- Images-must-not-have-duplicate-alt-text [auto]
- Images-alt-text-is-not-file-name [auto]
- Non-text-characters-in-accessible-name [auto]

## Assumptions

*There are currently no assumptions*

## Accessibility support

There are no major accessibility support issues known for this rule.

## Background

ORIGINAL ISSUE NOTES: Images must not have generic text alternatives (file name of the image source, duplicates, placeholders, etc.)

ORIGINAL ISSUE NOTES: Considerations:
- Duplicate alt texts
- Localisations

ORIGINAL ISSUE NOTES: 3 Rules (Semi):
- duplicate-alt-text
- file-name
- non-text-characters

### Pass example 1

Description...

```html
<!-- code -->
```

### Failure example 1

Description...

```html
<!-- code -->
```

### Inapplicable example 1

Description...

```html
<!-- code -->
```

**Comment by Brynanders** [comment]
Closing this down as we do not need a composed rule for the referenced checks.
