### ISSUE TITLE
Glossary Term of Namespaced Element within rule Orientation of the page is not restricted using CSS transform property [b33eff]

### ISSUE THREAD

**Issue by ChrisLoiselle** [auto-wcag/auto-wcag#1957]
The Glossary Term of Namespaced Element within rule Orientation of the page is not restricted using CSS transform property is listed within this page [b33eff]. Can anyone confirm why this is the case?

**Comment by Jym77** [comment]
Hi @ChrisLoiselle, I'm not sure I understand the question 🤔 
The Applicability of the rule starts with:
> This rule applies to any [HTML element](https://act-rules.github.io/rules/b33eff#namespaced-element) …

Where "HTML element" is a link to the definition of "Namespaced element" in the same page.
(i.e. it means "element in the HTML namespace" rather than "the element whose name is `html`")

**Comment by ChrisLoiselle** [comment]
@tombrunet , does this answer by @Jym77 provide clarity on your ask? It is an anchor link within the page itself.

**Comment by tombrunet** [comment]
@ChrisLoiselle Looks like this is done on most pages, so, that's fine. It's difficult to see the connection between "HTML element" and "Namespaced element", so that may be something that should be made clearer at some point, but I wouldn't make it a priority.

**Comment by ChrisLoiselle** [comment]
@tombrunet  ok, should we close the issue then ?

**Comment by WilcoFiers** [comment]
I think it's okay to close Chris.
