### ISSUE TITLE
Should inert iframes with focusable content fail? [akn7bn]

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#1965]
This related to the Iframe Iframe with interactive elements is not excluded from tab-order rule. It indicates that iframes with negative tabindex are a problem, but there's now another way to disable focus on iframe, by using `inert`.

I don't think iframes with `inert` should fail this rule, but I'd like other's opinion about that.

**Comment by giacomo-petri** [comment]
> I don't think iframes with inert should fail this rule, but I'd like other's opinion about that.

I agree; if the author consciously set the inert attribute to an iframe we should (?) assume that the intent is to prevent users navigating the iframe.

Side note: it's interesting how, setting the inert property to the iframe, it:
- allows mouse users to scroll and perceive visually the content of the iframe
- prevents keyboard and AT (such as screen readers) users to perceive the content of the iframe

setting instead the inert property to the body inside the iframe, it:
- allows mouse users to scroll and perceive visually the content of the iframe
- allows keyboard users to scroll using up/down arrows and perceive visually the content of the iframe
- prevents AT (such as screen readers) users to perceive the content of the iframe

**Comment by carlosapaduarte** [comment]
Initial discussion [in the CG call](https://www.w3.org/2023/02/09-act-r-minutes.html#t07). To be continued in the next meeting

**Comment by carlosapaduarte** [comment]
Update the applicability to exclude inert iframes and create our definition of inert, that includes the inter attribute and content outside a modal
