### ISSUE TITLE
Audio element content has transcript[2eb176]: should the transcript files be HTML?

### ISSUE THREAD

**Issue by kengdoj** [auto-wcag/auto-wcag#2021]
These test cases link to a .txt file with HTML for a transcript:

- Pass ex 2
- Pass ex 3
- Fail ex 2
- Fail ex 3

Should the Pass examples link to html files instead? I don't think code is acceptable in a transcript for the pass examples?

**Comment by carlosapaduarte** [comment]
We'll need to check all rules that use the same transcript files and update those also
