### ISSUE TITLE
autoplay rule [x0paj4] failed examples don't autoplay in major browsers

### ISSUE THREAD

**Issue by carlosapaduarte** [auto-wcag/auto-wcag#2030]
https://github.com/act-rules/act-rules.github.io/pull/1655#discussion_r1098674794 raises the issue about the failed example not working in Chromium browsers. A quick test reveals that the same happens in Firefox and Safari.

The way I see it, we have two choices:

- Deprecate the rule, since browsers have addressed the accessibility issue caught by this rule
- Change the applicability as suggested by @WilcoFiers in https://github.com/act-rules/act-rules.github.io/pull/1655#discussion_r1098674794, i.e., make it applicable to media elements that get turned on by scripts within 3 seconds of the page loading

**Comment by Jym77** [comment]
While building the Alfa semi-automated implementation, I had mixed result with that…
Sometimes the media did autoplay (often when opening the example from the rule page), sometimes it didn't (often when entering the URL directly).
I was also going to open such an issue, but more attempts show that stuff did autoplay sometimes 😖 And I'm not sure when exactly (this may also depend on devtools being open or not, on headset being connected or not, … 🙃 ) Tried both with Chrome and Firefox (on Windows 10).

**Comment by carlosapaduarte** [comment]
I'll check support for audio autoplay and for scripted auto-play and report back here

**Comment by carlosapaduarte** [comment]
I've run the tests. Results are the same for `audio` and `video` elements with audio content.

### Autoplay
- Firefox and Safari do not autoplay media content unless the user has instructed the browser to do so
- Chrome tries to learn the user behaviour and acts accordingly (which might explain why it [sometimes autoplayed](https://github.com/act-rules/act-rules.github.io/issues/2030#issuecomment-1424205479) for @Jym77). Chrome computes a [Media Engagement Index](https://developer.chrome.com/blog/autoplay/#media-engagement-index) to measure a user's "propensity to consume media on a site", and decides based on that to autoplay. I searched for this when, all of sudden, the examples that did not autoplay, started to autoplay after I manually played them.

### Scripted autoplay
- Chrome, Firefox and Safari all block it unless the user has instructed the browser to authorise it 
- This happens if there is an attempt to play the media before the user has interacted with the webpage, irrespective of the script running on load or after a timeout

**Comment by Jym77** [comment]
[MDN usage note on `play()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play#usage_notes):
> Although the term "autoplay" is usually thought of as referring to pages that immediately begin playing media upon being loaded, web browsers' autoplay policies also apply to any script-initiated playback of media, including calls to `play()`.
> (…)
> Note: The `play()` method may cause the user to be asked to grant permission to play the media, resulting in a possible delay before the returned promise is resolved. Be sure your code doesn't expect an immediate response.

---
And the [MDN Autoplay guide](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#autoplay_availability) states:
> As a general rule, you can assume that media will be allowed to autoplay only if at least one of the following is true:
> 
> * The audio is muted or its volume is set to 0
> * The user has interacted with the site (by clicking, tapping, pressing keys, etc.)
> * If the site has been allowlisted; this may happen either automatically if the browser determines that the user engages with media frequently, or manually through preferences or other user interface features
> * If the autoplay [Permissions Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy) is used to grant autoplay support to an [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) and its document.

---
So it does feel like modern UA are more or less solving the problem 🤔 

* We can deprecate the rule, under the assumption that users who don't want autoplay have already disabled it in their browser. This is easy 😄 This is a bit unsatisfactory given that SC 1.4.2 specifically refers to "web page" (OTOH without linking to the WCAG def), and if browsers already fix it, the SC itself might be obsolete (it was certainly needed back in the days of MySpace…)
* We could keep the rule, with a note that some users still have autoplay and the SC is needed for these. This is also unsatisfactory given that depending on the browser used to test, some examples autoplay (and are failing) while other don't (and are inapplicable). Which is pretty much what happened to both @carlosapaduarte and me. But it means these examples only fail depending on the accessibility support, and we don't really want them 😖

**Comment by Jym77** [comment]
Decision: move 1.4.2 as a secondary requirement since `autoplay` is possibly a WCAG failure, but not always.
