### ISSUE TITLE
[bc659a] Meta element has no refresh delay testcases generated incorrectly

### ISSUE THREAD

**Issue by tombrunet** [auto-wcag/auto-wcag#2039]
Testcases are being injected into the body element rather than the HTML element. For example:
```
<head>
	<meta http-equiv="refresh" content="30" />
</head>
<body>
	<p>This page refreshes after 30 seconds.</p>
</body>
```

is generated as 

```
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Failed Example 1</title>
</head>
<body>
	<head>
		<meta http-equiv="refresh" content="30" />
	</head>
	<body>
		<p>This page refreshes after 30 seconds.</p>
	</body>
</body>
</html>
```

The resulting html doesn't seem to be the intent of the testcase.

**Comment by Jym77** [comment]
IIRC, that should be solved if we include the `html` element in the test case, then it won't be added incorrectly.
We'll need to also keep the `lang` attribute and the `title` element, so that the case don't fail other SC 🙈

**Comment by tombrunet** [comment]
Noticed that the same is happening for bisz58

**Comment by tombrunet** [comment]
Looks like this was fixed, but not sure when. Closing.
