### ISSUE TITLE
Wrong MIME type for rabbit-video/video.mp4

### ISSUE THREAD

**Issue by dd8** [auto-wcag/auto-wcag#2053]
The MIME type for https://www.w3.org/WAI/content-assets/wcag-act-rules/test-assets/rabbit-video/video.mp4 used to be `video/mp4`

The MIME type is now `application/mp4` - which indicates the MP4 contains no video or audio according to [RFC 4337](https://datatracker.ietf.org/doc/html/rfc4337#section-2)

This no longer matches the applicability of the rule because it's not an audio or video MIME type:
https://act-rules.github.io/rules/8fc3b6#applicability

That means failed example 2 no longer fails because it uses the rabbit video:
https://act-rules.github.io/rules/8fc3b6#failed-example-2

Here are the headers from Chrome DevTools

**General**
Request URL: https://www.w3.org/WAI/content-assets/wcag-act-rules/test-assets/rabbit-video/video.mp4
Request Method: GET
Status Code: 200 
Remote Address: 104.18.22.19:443
Referrer Policy: strict-origin-when-cross-origin

**Response Headers**
accept-ranges: bytes
access-control-allow-origin: *
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cache-control: max-age=600
cf-cache-status: BYPASS
cf-ray: 7ba369df9a5f0764-MAN
content-length: 1053651
content-security-policy: upgrade-insecure-requests
content-type: application/mp4
date: Wed, 19 Apr 2023 07:25:26 GMT
etag: "643e940c-1013d3"
expires: Wed, 19 Apr 2023 07:35:16 GMT
last-modified: Tue, 18 Apr 2023 12:58:52 GMT
permissions-policy: interest-cohort=()
server: cloudflare
strict-transport-security: max-age=15552000; includeSubdomains; preload
vary: Accept-Encoding
via: 1.1 varnish
x-backend: www-mirrors
x-cache: HIT
x-cache-hits: 1
x-fastly-request-id: c680f5cc124891ad4e90df37dd6c20683b982967
x-github-request-id: CAAE:82BE:126E82A:1A5B344:643F975C
x-origin-cache: HIT
x-proxy-cache: MISS
x-request-id: 7ba369df9a5f0764
x-served-by: cache-lga21920-LGA
x-timer: S1681889127.773894,VS0,VE2

**Comment by WilcoFiers** [comment]
@dd8 Assigned to Daniel. This is a W3C server question, so not something we can control directly. We'll try to get it fixed though.

**Comment by daniel-montalvo** [comment]
Our Systems team is investigating this at the moment. GitHub pages and CloudFlare may be involved in this behavior as well. I'll update this issue when there is updates to that.

**Comment by gosko** [comment]
This seems to be a bug in GitHub Pages. I started [a discussion on the GitHub community site](https://github.com/orgs/community/discussions/58259) to see if anyone has an idea about this, and hopefully get someone's attention at GitHub. If that doesn't accomplish anything I will try to contact GitHub support. I think this behavior likely changed due to [this recent update to the mime-db project](https://github.com/jshttp/mime-db/commit/48e411522aed9925570b6c6bbf0bbc331242c038), on Feb 5.

**Comment by gosko** [comment]
This issue with GitHub Pages has now been fixed.

**Comment by daniel-montalvo** [comment]
Just tried it now and content-type is now video/mp4.


Closing. Thanks @gosko  for your involvement in this.
