### ISSUE TITLE
Contrast rules should account for CJK text size [afw4f7] [09o5cg]

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#2068]
This was brought up by Makoto in the most recent AGWG survey. A CJK text should not be considered large text until it has 22pt, or 18pt if bold.

This is a problem with the [large scale text](https://www.w3.org/WAI/standards-guidelines/act/rules/afw4f7/proposed/#large-scale-text) definition. It impacts both our contrast minimum and contrast enhanced rule.

**Comment by giacomo-petri** [comment]
It appears that the specific font size measurements of 22pt, or 18pt if bold, are specifically tailored for the Japanese language. However, based on the conversation, it is unclear whether these metrics are applicable to Chinese, Korean, or other languages.

Considering this uncertainty, should we consider adding a general message stating that these measurements are intended for Latin languages and that non-Latin languages may require different values? While it raises ethical considerations, it seems that there are no official guidelines available for other languages at the moment.

Additionally, it is intriguing that the definition of large text for the Japanese language is only specified in the Japanese version of the WCAG. This raises the question of whether someone evaluating a Japanese website might refer to the English version of the WCAG and miss the specific requirements for large text in Japanese.

**Comment by Jym77** [comment]
WCAG [large text](https://www.w3.org/TR/WCAG21/#dfn-large-scale) does have a provision for CJK. So I guess we should indeed have a similar one.
