### ISSUE TITLE
Disconnect of communication between CG and TF

### ISSUE THREAD

**Issue by HelenBurge** [auto-wcag/auto-wcag#2071]
There has been a gradual breakdown of communication between the task force and community group. This is often highlighted by pull requests where the TF have discussed and agreed from reviews in https://docs.google.com/spreadsheets/d/1OSkPFocXk4K3zYLnwS78WLsWO4PvE5yRcsauyefuIUI/edit#gid=1605073031 and then discussed in a meeting, and the action items done in the PR: https://github.com/act-rules/act-rules.github.io/pull/2064

As seen from the comments from @Jym77 some decisions made are not clear to the community group.

We also have had issues of large changes being discussed and agreed, without getting agreement from CG until items are in progress.

It would be good to get a more formal way of sharing information. We used to rely on one person to share information, but maybe a more formal process would be good?

Please suggest ideas for ways we can improve the current situation.

**Comment by Jym77** [comment]
From my point of view (hat on: CG person that tend to review every PR), I often see the following effects:
* Some changes get suggested by TF, without giving any context for them, causing a lot of confusion. (lack of communication TF => CG).
* Some changes get suggested by TF, which seems to contradict some decisions the CG took (or disregard some discussions we had about corner cases). It feels like the TF has lost the context under which the CG made some decision and goes through the same issues again. (lack of communication CG => TF).
* TF decides some changes and start making it without warning. (feeling of CG being ignored/disregarded) (I think we're not too bad on that point, notably we're managing to have deep discussion on the secondary requirements or the stateful rules, so we are actually OK for discussing the bigger items between us).

**Comment by WilcoFiers** [comment]
This has been put on the agenda for Thursday's TF call. I'll wait with comments until that conversation has happened.

**Comment by HelenBurge** [comment]
From comments made in the meeting:
1. The PR format needs to be updated to add more background information.
2. The main items from Task Force are not always discussed as items are suggested for the agenda but may not be discussed - agreed that Helen will let CG chairs know when items are important to have at the top of the agenda.
3. The big items are being discussed via GitHub and both sides feel heard. However, it might be good to have a mixed meeting when the back and forths are not progressing as expected. This will be done when deemed important.
4. CG chairs agree with most - but would like more focus on documenting items as easier to keep up. To not use issues/pull requests but discussion threads.

**Comment by WilcoFiers** [comment]
We've invited the CG chairs to join ACT TF for a conversation on this topic for the June 29th call.

**Comment by daniel-montalvo** [comment]
Discussion in our [TF 29 June meeting](https://www.w3.org/2023/06/29-wcag-act-minutes.html#t02)

**Comment by WilcoFiers** [comment]
The main issue we've discovered is that not enough background information is included. Going forward PRs that come from ACT TF will link to the survey. Resolutions from discussing should be included in the pull requests as well. Going forward the liaison of a rule will take notes on what changes are requested, which should hopefully prevent confusion about what changes were requested.

We're going to try this updated process and are closing this issue. If this proves insufficient we'll revisit.
