### ISSUE TITLE
Should ARIA reference rule check aria-activedescendant?

### ISSUE THREAD

**Issue by dd8** [auto-wcag/auto-wcag#2097]
The rule description says it checks that every ID reference required by WAI-ARIA exists:
https://www.w3.org/WAI/standards-guidelines/act/rules/in6db8/proposed/

But the rule only applies to aria-controls although the text for aria reference processing says:

> Any aria-activedescendant value that does not match an existing ID reference exactly is an author error and will not match any element in the DOM.

https://www.w3.org/TR/wai-aria-1.2/#mapping_additional_relations_error_processing

**Comment by Jym77** [comment]
Related to https://github.com/w3c/aria/issues/1970
Closing this one, waiting to see what ARIA does.
