### ISSUE TITLE
URL normalization

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#211]
---
title: URL normalization 
key: url-normalization 
---

A process to transform URLs in a standardised and consistent way, to make it possible to determine if two syntactically different URLs may be equivalent. (Source: [Wikipedia](https://en.wikipedia.org/wiki/URL_normalization)).

Several types of URL normalization exists. Some types of normalization preserve the semantics of the URL, some usually preserve the semantics, and some types change the semantics. 

For the purpose of ACT rules, we only consider the types of URL normalization that preserve the semantics of the URL. These normalization types are: 
- [Case Normalization](https://tools.ietf.org/html/rfc3986#section-6.2.2.1)
- [Percent-Encoding Normalization](https://tools.ietf.org/html/rfc3986#section-6.2.2.2)
- [Scheme-Based Normalization](https://tools.ietf.org/html/rfc3986#section-6.2.3)

[Relative URLs](https://www.w3.org/TR/WD-html40-970917/htmlweb.html#relative-urls) first need to be resolved to full URLs before doing the comparison.

**Comment by jribbens** [comment]
https://url.spec.whatwg.org/ is relevant to this, even if the specification document itself is ... poor.

**Comment by jribbens** [comment]
Also consider IDNA.

**Comment by jkodu** [comment]
Close - PR - https://github.com/auto-wcag/auto-wcag/pull/220
