### ISSUE TITLE
"Semantic role" does not specify case-sensitivity

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#214]
The current definition of "semantic role" does not explicitly state whether the tokens of the `role` attribute are case-sensitive or not. Per the [Core Accessibility API Mappings](https://www.w3.org/TR/core-aam/#mapping_role), case sensitivity of the `role` attribute is inherited from the host language, in our case HTML. This doesn't really help the situation as the `role` attribute in HTML is a list of space-separated tokens for which the following note is included:

> How tokens in a set of space-separated tokens are to be compared (e.g., case-sensitively or not) is defined on a per-set basis.

https://www.w3.org/TR/html/infrastructure.html#space-separated-tokens

For the `role` attribute, it is however never defined whether the tokens are case-sensitive or not: 

> The attribute, if specified, must have a value that is a set of space-separated tokens; each token must be a non-abstract role defined in the WAI-ARIA specification [wai-aria-1.1].
>
> The WAI-ARIA role that an HTML element has assigned to it is the first non-abstract role found in the list of values generated when the role attribute is split on spaces.

https://www.w3.org/TR/html/dom.html#aria-role-attribute

As can be witnessed by a quick search on Google, this ambiguity has led to different handling of case-sensitivity of the `role` attribute in browsers and AT: https://www.google.dk/search?q=aria+role+case+sensitive

How might we go about handling this? Would it possible to introduce something akin to "accessibility support" for definitions where we can state that some browsers and AT treat the `role` attribute as case-sensitive?

**Comment by kasperisager** [comment]
To add to the confusion, ARIA in HTML specifies that _authors_ must use lowercase letters for the `role` and `aria-*` attributes: https://www.w3.org/TR/html-aria/#case-sensitivity

**Comment by annethyme** [comment]
Add a note on this to the semantic role algorithm?

**Comment by WilcoFiers** [comment]
Go for it.

**Comment by annethyme** [comment]
Being handled by https://github.com/auto-wcag/auto-wcag/pull/442
