### ISSUE TITLE
Inapplicable examples should be failed if considered applicable (at least ff89c9)

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#2145]
I stumbled upon an automated implementation of ARIA required context role (ff89c9) that did not limit its scope to explicit roles, but also took into consideration implicit roles, unlike the ACT Rule Applicability: https://www.w3.org/WAI/standards-guidelines/act/rules/ff89c9/proposed/

The tool reported a consistent implementation of the rule, but when looking into the Test Cases for the rule, the Inapplicable testcase for exactly this (Inapplicable Example 2) was reported as Passed, not Inapplicable. Since this is allowed in a consistent implementation, basically "Inapplicable" test cases will in general only work if they are written in a way that they will be Failed, if they are considered applicable to the rule.

**Comment by carlosapaduarte** [comment]
Discussed in the last meeting and all implementors agreed that the current mapping is working as it should, to support tools that do not implement the rule exactly as specified but still do not cause false positives.
