### ISSUE TITLE
Form field has non-empty accessible name [e086e5]: add 1.3.1 and 2.5.3

### ISSUE THREAD

**Issue by kengdoj** [auto-wcag/auto-wcag#2166]
Please reference the [comment on this issue](https://github.com/w3c/wcag/pull/2057/files#r1516398862) regarding applicable SCs: 

> a control with visible label text but no accessible name would fail 1.3.1, 2.5.3, and 4.1.2

**Comment by carlosapaduarte** [comment]
Add as secondary requirements

**Comment by giacomo-petri** [comment]
PR merged, closing ticket
