### ISSUE TITLE
Scrollable regions should pass when there is an open modal [0ssw9k]

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#2217]
The [Scrollable content can be reached with sequential focus navigation
](https://www.w3.org/WAI/standards-guidelines/act/rules/0ssw9k/proposed/), rule does not account for scrollable regions that are covered by the backdrop of a modal. While a model is open, it is perfectly reasonable for scrollable regions not to have focusable elements inside them.

**Comment by Jym77** [comment]
I guess it should more generally hook on [inert subtrees](https://html.spec.whatwg.org/multipage/interaction.html#inert-subtrees), which includes [being blocked by a modal](https://html.spec.whatwg.org/multipage/interaction.html#modal-dialogs-and-inert-subtrees).

**Comment by giacomo-petri** [comment]
Do we want to adjust the applicability to make this scenario inapplicable, or should we find a way to include it in the passing examples? (The first option is easier 😆)

Edit: Actually, the second option is more accurate. I'll go with it.
