### ISSUE TITLE
Missing test case descriptions for unique id rule

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#228]
Please add test descriptions to the rule - https://auto-wcag.github.io/auto-wcag/rules/SC4-1-1-unique-id.html

**Comment by Brynanders** [comment]
@jkodu It looks like you are refrring to #110 is that correct? If so, I am unable to edit. 
![image](https://user-images.githubusercontent.com/37368581/45500021-8548d680-b775-11e8-9f1b-eea4b8947bb1.png)

**Comment by annethyme** [comment]
PR: https://github.com/auto-wcag/auto-wcag/pull/256
