### ISSUE TITLE
Make Algorithms more visible on https://auto-wcag.github.io/auto-wcag/

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#235]
It would be nice to have a list of all Algorithms on https://auto-wcag.github.io/auto-wcag/, so that it's easy to get an overview of them - at least when writing rules, but maybe also when implementing them or evaluating the rules framework.

**Comment by annethyme** [comment]
They are already there, so I'm changing the title of this issue from "Add Algorithms overview to https://auto-wcag.github.io/auto-wcag/" to "Make Algorithms more visible on https://auto-wcag.github.io/auto-wcag/"

**Comment by jkodu** [comment]
PR - https://github.com/auto-wcag/auto-wcag/pull/320
