### ISSUE TITLE
Improve sticky headers on auto-wcag.github.io

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#246]
The sticky headers on https://auto-wcag.github.io/auto-wcag does not work so well when using zoom. They take up most of the screen then.

And when using the local anchors to get to the definitions at the bottom of the page, the heading that you are arriving at is hidden under the higher-level heading that is sticky.

Any great ideas on how to fix these things?

**Comment by jkodu** [comment]
Underlying static site generators, layout and themes are going to be changed. In view of those changes, this issue is no longer relevant.
