### ISSUE TITLE
"Glossary" instead of "Definitions"?

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#247]
Just saw that at least WCAG uses the term ”Glossary” for what we call ”Definitions”: https://www.w3.org/TR/WCAG21/#glossary

Wondering if we should align?

Especially since we have a part of our rules called “Test Definition”..,.

**Comment by annethyme** [comment]
Yes for renaming

**Comment by gianwild** [comment]
Yes for renaming

Cheers,
Gian

**Comment by WilcoFiers** [comment]
Sounds good to me. Feel free to put together a PR.

**Comment by jkodu** [comment]
Todo:
- Change to glossary
- Enhance glossary page to have `key`
- Glossary listing to be tabulated with title and key

**Comment by jkodu** [comment]
PR - https://github.com/auto-wcag/auto-wcag/pull/320
