### ISSUE TITLE
minor changes for rules

### ISSUE THREAD

**Issue by josehilera** [auto-wcag/auto-wcag#26]
Here I suggest some [minor changes](https://docs.google.com/spreadsheets/d/1MYr6b8KsCNZNT9Q9LQXL9-K4jn3l98bGjylDnn0WFro/edit?usp=drivesdk) for rules

**Comment by josehilera** [comment]
Here I suggest some minor changes for rules.
https://docs.google.com/spreadsheets/d/1MYr6b8KsCNZNT9Q9LQXL9-K4jn3l98bGjylDnn0WFro/edit?usp=drivesdk

**Comment by josehilera** [comment]
My suggestion of minor changes for each rule, in plain text:

- SC1-1-1-aria-describedby: Add "User expertise and skills" property. Put DOM instead "rendered page". Add pointer.
- SC1-1-1-css-image: Use {{ page.rule_id }} in outcomes testcase and ID properties. There is not css selector. Steps 3, 4 must be manual. Add repair and required interaction properties. Put DOM instead "rendered page". Add pointer property.  
- SC1-1-1-longdesc	: Use {{ page.rule_id }} in outcomes testcase and ID properties. Step 3 must be manual. Put DOM instead "rendered page". Change "requir" by repair. Add pointer.
- SC1-1-1-text-alternative: Use {{ page.rule_id }} format in outcomes testcase and ID properties. Steps 4, 6, 7, 8, 13, 15, 17, 18 must be manual. Add required interaction property in step 12 and 15. Put DOM instead "rendered page". Add pointer. Change "requir" by repair. 
- SC1-4-2-audio-control-audio: Use {{ page.rule_id }} format in outcomes testcase and ID properties. Add User expertise and skill. Step 6 must be manual. Add repair property in questions. Step 5 does not need question. Add pointer.
- SC2-2-1+SC3-2-5-meta-refresh: Add author.
- SC2-4-7-focus-in-viewport: Add author. Add pointer.
- SC3-1-1-html: Put the css selector. Change "Do nothing. (This case is covered by SC3-1-1-xml-lang.)" by "execute rule SC3-1-1-xml-lang". Add pointer.
- SC3-1-1-text: Put the css selector. Add table with question properties in step 2. Add pointer.
- SC3-1-2-xml-lang	Put the css selector. Add pointer.
- SC4-1-1-accesskey: ok.
- SC4-1-1-id: ok.
- SC4-1-1-idref: ok.
- SC4-1-1-idrefs: Add test name in the table.
- SC4-1-1-tag-nesting: Add test name in the table.
- SC4-1-1-unique-attrs: Add test name in the table. Add cas selector. Environment perhaps should be DOM.
- SC4-1-2-button: Add test name in the table. Add author. Add pointer.

**Comment by WilcoFiers** [comment]
@josehilera Can you work on a pull request that contains these changes?

**Comment by josehilera** [comment]
@WilcoFiers I cloned the repository, made locally changes in _rules files, but I cannot push the local repository. I think that you must give me permission as a member.

**Comment by josehilera** [comment]
I have included pending changes of the list in PR32.
