### ISSUE TITLE
Suggestion: Use RDF pointers for test targets in test cases

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#266]
The current approach to specifying test targets in test cases is by using a custom `data-*` attribute, namely `data-rule-target`, which has a couple of drawbacks:

- Only test targets that are HTML or SVG elements can currently be specified. We do however have rules that require us to specify e.g. attribute nodes as test targets.
- If we were to introduce additional methods for targeting different types of content, we'd end up with potentially multiple ways of specifying test targets, rather than a single uniform approach.

I'd therefore recommend that we find a way to incorporate [Pointer Methods in RDF](https://www.w3.org/TR/Pointers-in-RDF/), which is also the kind of pointers used in the EARL and, by extension, the ACT Data Format. Rule authors would then have a much wider range of options available for specifying test targets and we could provide further pointer methods as needed. Using this approach, each test case would consist of two pieces of information:

- A fixture representing the test aspects involved; HTTP, HTML, CSS, etc.
- A pointer to a test target within the test aspects, to which the test case applies.

One way to supply these could be to specify two code blocks for each test case: One for the fixture in whatever language makes sense and then a JSON-LD representation of the pointer, e.g.:

```html
<div class="foo">
  <p>This is the test target</p>
</div>
```

```json
{
  "ptr:CSSSelectorPointer": {
    "ptr:expression": ".foo > p"
  }
}
```

For brevity, we could leave out `@context` as I've done above and simply inject one as part of the build process. This approach would also lend itself well to tooling support as we could then validate the pointers as part of the build process.

Thoughts?

**Comment by jkodu** [comment]
@kasperisager 
I believe this issue is not relevant after our discussion during f2f meeting.

Please re-open if you think otherwise.
