### ISSUE TITLE
Exported test cases are incorrect

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#289]
There seems to be something wrong with the exported test cases found at https://auto-wcag.github.io/auto-wcag/auto-wcag-testcases/testcases.json. For example, this test fixture https://auto-wcag.github.io/auto-wcag/auto-wcag-testcases/assets/SC4-1-1-unique-id_inapplicable_example_1.html is _not_ "inapplicable example 1" as both the URL and JSON file indicate; it's actually "passed example 2".

**Comment by kasperisager** [comment]
Also, test cases that are not HTML documents should not be exported as such, e.g. SVG documents.

**Comment by jkodu** [comment]
@kasperisager, so the contents of the test case needs to be parsed to figure out of it is an svg, and you would want them to be `filename.svg` files?

**Comment by kasperisager** [comment]
Exactly 👍 Otherwise, browsers will interpret the files as HTML documents and parse them as such.

**Comment by kasperisager** [comment]
Case in point: https://auto-wcag.github.io/auto-wcag/auto-wcag-testcases/assets/SC2-4-2-page-has-title_inapplicable_example_1.html currently fails the associated rule as the document, whose root is an `<html>` element due to it being interpreted as HTML, does not contain a `<title>`.

**Comment by jkodu** [comment]
@kasperisager - PR - https://github.com/auto-wcag/auto-wcag/pull/299
