### ISSUE TITLE
Meta-refresh no delay: Interpretation of "bigger than" is questionable

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#290]
Consider the following example from https://auto-wcag.github.io/auto-wcag/rules/SC2-2-1+SC3-2-5-meta-refresh.html:

```html
<head>
  <meta http-equiv="refresh" content="72000; http://example.com" />
</head>
```

This is currently listed as a pass, even though it fails the expectation; the delay is not _bigger than_ 72000, but rather _bigger than or equal to_ 72000. The WCAG uses the term "larger", but the same thing applies:

> **20 Hour Exception:** The time limit is longer than 20 hours.

https://www.w3.org/TR/WCAG/#timing-adjustable

**Comment by annethyme** [comment]
Handled by https://github.com/auto-wcag/auto-wcag/pull/307. Please review.
