### ISSUE TITLE
Update rule - Aria Allowed Attribute

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#303]
Based on comments here and following the thread - https://github.com/auto-wcag/auto-wcag/pull/231#issuecomment-429764563, the published rule https://auto-wcag.github.io/auto-wcag/rules/SC4-1-1+SC4-1-2-aria-allowed-attribute.html needs updates.

**Comment by annethyme** [comment]
Handled by https://github.com/auto-wcag/auto-wcag/pull/311
