### ISSUE TITLE
aria-hidden with focusable content: Incorrect test case

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#314]
The following test is currently listed as passing https://auto-wcag.github.io/auto-wcag/rules/SC4-1-2-aria-hidden-focus.html even though the `<button>` actually fails the rule:

```html
<div aria-hidden="true" data-rule-target>
  <button tabindex="-1">Some button</button>
</div>
```

While the `<button>` has been removed from the sequential focus navigation order, it is still very much focusable.

**Comment by annethyme** [comment]
@jkodu, I am assigning this rule to you since you are the owner of this rule inside the WAI-Tools project. It has a deadline of March 31.

**Comment by annethyme** [comment]
Being handled by https://github.com/auto-wcag/auto-wcag/pull/439
