### ISSUE TITLE
HTML Page has a title: Expectation is ambiguous

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#316]
This is basically the same issue as #315, just for https://auto-wcag.github.io/auto-wcag/rules/SC2-4-2-page-has-title.html, and relates to the fact that the term _contain_ is not defined. Consider the following snippet of HTML:

```html
<div>
  <title>I'm not rendered</title>
</div>

<script>
  {
    const host = document.querySelector("div");
    const root = host.attachShadow({ mode: "open" });

    root.innerHTML = `
      <p>I'm rendered</p>
    `;
  }
</script>
```

In well-defined terms, the `<div>` has the following:

- A single [descendant](https://www.w3.org/TR/dom41/#concept-tree-descendant): `<title>I'm not rendered</title>`.
- Two [shadow-including descendants](https://www.w3.org/TR/dom41/#concept-shadow-including-descendant): `<title>I'm not rendered</title>` and `<p>I'm rendered</p>`.
- A single [descendant](https://www.w3.org/TR/dom41/#concept-tree-descendant) in the [flat tree](https://drafts.csswg.org/css-scoping/#flat-tree): `<p>I'm rendered</p>`.

Opposite #315, the first two options will cause the rule to pass, while the third option will cause the rule to fail. 

As an aside, Chrome actually picks up the `<title>` even though its not included in the flat tree.

**Comment by annethyme** [comment]
@WilcoFiers, could we maybe take this up on the f2f next week?

**Comment by annethyme** [comment]
@kasperisager, can Siteimprove come up with a proposal?

**Comment by annethyme** [comment]
Will be handled by https://github.com/auto-wcag/auto-wcag/pull/432
