### ISSUE TITLE
Discuss permission management

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#341]
**The problem**

Currently we make everyone who wants to write, update, or even review rules as contributors. This gives them full read / write permissions on the auto-wcag repository. This lets users do everything they need, like raise PRs, edit them, approve them, etc. But this also lets people do things that they probably shouldn't be able to do, such as change other people's comments, merge PRs before that weren't approved by people from 3 different organisations, or as recently happened with #323 and #284 these PRs got merged before they were discussed on an Auto-WCAG call.

**Comment by jkodu** [comment]
We discussed this and appropriate permissions are set on the repository now.
