### ISSUE TITLE
meta-refresh rule: issue with test cases

### ISSUE THREAD

**Issue by carlosapaduarte** [auto-wcag/auto-wcag#351]
While working on the implementation of this rule we came across a possible issue with one test case. The applicability specifies the target is valid `<meta http-equiv="refresh">` element. According to the HTML spec (https://www.w3.org/TR/html/document-metadata.html#statedef-http-equiv-refresh) the content attribute should consist of a non-negative integer or a non-negative integer plus a semicolon plus one or more spaces plus URL (case insensitive) plus the equal sign plus a valid url.

Passed example 2 and 3, and failed example 3 and 4 don't follow this spec (they miss the URL= part). Shouldn't they be moved to the inapplicable section?

**Comment by kasperisager** [comment]
Not quite and that's where the "refresh" vs. "redirect" part comes to play. Per steps 8 and 9 in the linked spec, the URL defaults to that of the node document (step 8) and if there are no more characters left, the process skips to the end (step 9). As such, something like this...

```html
<meta http-equiv="refresh" content="30">
```

...would "refresh" the document, as in "redirect" to itself, after 30 seconds.

**Comment by annethyme** [comment]
@carlosapaduarte, can you agree to the comment by @kasperisager?

**Comment by annethyme** [comment]
Closing issue, since it seems resolved to me. 
@carlosapaduarte, let me know if you want me to reopen it again.

**Comment by carlosapaduarte** [comment]
My original concern was not caused by the absence of the URL in @kasperisager example
`<meta http-equiv="refresh" content="30">`

My concern comes from examples such as this
`<meta http-equiv="refresh" content="5; http://example.com" />`
where there is no URL string in the content attribute. According to the linked spec if the content attribute has more than a non-negative integer then URL should be there after the semicolon
