### ISSUE TITLE
Dropdown focus styles

### ISSUE THREAD

**Issue by IschaGast** [auto-wcag/auto-wcag#356]
I was using my keyboard to navigate through the site but lost my focus when I was on a dropdown link.

Removing this would fix it :) 

```
.dropdown-toggle:focus {
    outline: 0;
}
```

![nov-21-2018 13-54-15](https://user-images.githubusercontent.com/39517/48842612-f8ce1c00-ed94-11e8-8ddc-3cfcab070274.gif)

**Comment by jkodu** [comment]
PR in place. Closing issue.
