### ISSUE TITLE
Update Rule: Form field has accessible name

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#364]
Rule -https://auto-wcag.github.io/auto-wcag/rules/SC3-3-2+SC4-1-2-form-field-has-name.html

@ShadowBB believes that this rule should not refer to SC 3.3.2, because, the SC only asks for a label/ accessible name to exist and not for the label to be associated with the form field.
- https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html

Excerpt:
`3.3.2 Labels or Instructions: Labels or instructions are provided when content requires user input. (Level A)`

Suggestion: 
- Remove SC 3.3.2 from the rule

**Comment by kasperisager** [comment]
Given that https://www.w3.org/TR/WCAG20-TECHS/G162.html on its own is a sufficient technique for 3.3.2, I do agree with the suggested changes.

**Comment by jkodu** [comment]
PR in place. Closing issue.
