### ISSUE TITLE
Should "Role attribute has valid value" only apply to elements that do not have an implicit role?

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#373]
The implicit role of an element, if one exists, effectively counts as a fallback role, and as such something like this...

```html
<button role="knap">I'm a button!</button>
```

...will still behave correctly.

**Comment by kasperisager** [comment]
Summoning @ShadowBB who brought this up during validation of our implementation of the rule.

**Comment by WilcoFiers** [comment]
Is this a theoretical question, or is there an example of this producing a false positive somewhere?

**Comment by kasperisager** [comment]
Yep: https://www.accessibility.nl/wai-tools/validation-test-sites/starten-en-groeien-den-bosch-ondernemen/. That page does stuff like this:

```html
<header class="header" role="header">
  ...
</header>
```

**Comment by kasperisager** [comment]
Given that this passes...

```html
<div class="header" role="header banner">
  ...
</div
```

...I absolutely think the case in https://github.com/auto-wcag/auto-wcag/issues/373#issuecomment-448126589 should pass as well.

**Comment by WilcoFiers** [comment]
I see, but I'd argue that all roles should be valid, not just one of them. Fallback roles are to handle lack of support for stuff. They aren't there for people to just make up stuff.

**Comment by kasperisager** [comment]
That's a really good point as well. I do agree that would be the better approach! It definitely has to be coupled with an assumption then.

**Comment by ShadowBB** [comment]
How is this for an assumption "This rule assumes ARIA is being used to comply to WCAG". This is becoming a sort of "catch all" assumption for me with these sort of rules and would lump this discussion in in the larger discussion on aria "spellchecking" rules.

**Comment by annethyme** [comment]
Maybe we could make the assumption more specific? E.g.:
"This rule assumes ARIA is being used to convey user interface behaviors and structural information to assistive technologies, that are not in other ways conveyed."

**Comment by ShadowBB** [comment]
@annethyme That more specific assumption works for me.

**Comment by jkodu** [comment]
PR #402, hence closing this issue.
