### ISSUE TITLE
Should "ARIA allowed attribute" limit itself to only elements included in the accessibility tree?

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#375]
Same reasoning as outlined in https://github.com/auto-wcag/auto-wcag/issues/372#issuecomment-447663254. Discussed with @ShadowBB during evaluation of the rule in Alfa.

**Comment by annethyme** [comment]
Being handled in https://github.com/auto-wcag/auto-wcag/pull/436
