### ISSUE TITLE
SC1-4-2-audio-control-audio won't catch audio not inserted in the DOM

### ISSUE THREAD

**Issue by 2biazdk** [auto-wcag/auto-wcag#40]
I looked at this rule:
https://github.com/auto-wcag/auto-wcag/blob/master/_rules/SC1-4-2-audio-control-audio.md

And it only takes audio into account, if the audio element is inserted in the DOM. But audio can be auto-played by doing:

```js
var audio_object = new Audio('sample-audio.mp3');
audio_object.play();
```

This will not be caught by the rule currently, as the CSS selector will not be able to find this audio instance.

**Comment by WilcoFiers** [comment]
@2biazdk Do you want to continue work on this?

**Comment by 2biazdk** [comment]
@WilcoFiers Sure. Anything specific that needs doing? Should I just improve upon it and bring it up to date with ACT?

**Comment by WilcoFiers** [comment]
@2biazdk Can you propose an update for the rule? I'm happy to work with you on this, if you can come up with a proposal, we'll take it from there. Please follow the new workflow:
https://github.com/auto-wcag/auto-wcag/issues/14

**Comment by 2biazdk** [comment]
---
rule_id: SC1-4-2-audio-control-audio
name: Audio control
test_mode: semi-automatic

criteria:
- 1.4.2 # Audio Control (Level A)

authors:
- Frank Berker
- Tobias Christian Jensen
---

## Description

This test looks at sounds that are played automatically after the web page has loaded, and checks that the sound is no longer than 3 seconds or that there is a mechanism at the top of the web page to control the sound.

## Background

- [G60: Playing a sound that turns off automatically within three seconds](http://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140916/G60)
- [G170: Providing a control near the beginning of the Web page that turns off sounds that play automatically](http://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140916/G170)
- [G171: Playing sounds only on user request](http://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140916/G171)
- [F23: Failure of 1.4.2 due to playing a sound longer than 3 seconds where there is no mechanism to turn it off](http://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140916/F23)
- [F93: Failure of Success Criterion 1.4.2 for absence of a way to pause or stop an HTML5 media element that autoplays](http://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140916/F93)

## Assumptions

- The test assumes that audio is rendered in the `audio` element. Therefore this test exclusively checks audio content in the `audio` element.
- The test assumes that video is rendered in the `video` element. Therefore this test exclusively checks video content in the `video` element.
- This test states that the links or buttons for the mechanism to control the sound is one of the first five links or buttons on the web page. This is more specific than the WCAG documentation.

## Test procedure

### Selector

Select all elements that match the following CSS selector(s):

- audio
- video

If no elements are found, go to [step 5][#step-5].

### Step 1

Check the `paused` property on the element.

If set to true, return [step1-pass](#step1-pass)

Else continue with [step 2](#step-2)

### Step 2

Check the `muted` property of the element.

If set to true, return [step2-pass](#step2-pass)

Else continue with [step 3](#step-3)

### Step 3

Check that the `duration` property on the element is shorter than or equal to 3 seconds.

If the condition is true, continue with [step 4][#step-4]

Else continue with [Step 5](#step-5)

### Step 4

Check the `loop` property on the element.

If set to true true, continue with [Step 5](#step-5)

Else, return [step4-pass](#step4-pass)

### Step 5

Check if the element plays audio for more than 3 seconds.

If the user is not available, return [step5-cannottell](#step5-cannottell)

**User Input Question:**

| Property     | Value
|--------------|---------
| highlight    | Web page with an automatically started sound.
| question     | Is audio playing on the web page?
| help         | There should not be audio playing automatically on the web page.
| user_profile | Requires hearing
| context      | yes
| interaction  | no

If yes, continue with [Step 6](#step-6).

Else, return [step5-pass](#step5-pass)

### Step 6

Check if a mechanism to control the sound is provided as one of the first five links or buttons on the web page.

If the user is not available, return [step6-cannottell](#step6-cannottell)

**User Input Question:**

| Property     | Value
|--------------|---------
| highlight    | Web page with an automatically started sound.
| question     | Does the web page provide a mechanism to control the sound as one of the first five links or buttons?
| help         | A mechanism to pause or stop the video or audio, or control the volume or mute the audio must be available on the web page. The mechanism must be located as one of the first five links or buttons of the web page. This way people with screen readers can turn off the sound before reading the web page. To inspect this, use the tab key to navigate through the web page.
| user_profile | Requires hearing
| context      | yes
| interaction  | yes

If yes, return [step6-pass](#step6-pass)

Else, return [step6-fail](#step6-fail)

## Outcome

The resulting assertion is as follows,

| Property | Value
|----------|----------
| type     | Assertion
| test     | auto-wcag:{{ page.rule_id }}
| subject  | *the selected element*
| mode     | auto-wcag:{{ page.test_mode }}
| result   | <One TestResult from below>

### step1-pass

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Passed
| description | The audio is paused and does not play automatically.

### step2-pass

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Passed
| description | The audio is muted and does not play out loud automatically.

### step4-pass

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Passed
| description | The audio duration is no longer than 3 seconds.

### step5-cannottell

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | CannotTell
| description | It is not possible to determine if there is audio playing on the web page.

### step5-pass

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Passed
| description | No audio longer than 3 seconds is playing on the web page.

### step6-cannottell

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | CannotTell
| description | It is not possible to determine if the web page provides a mechanism to control the audio as one of the first five links or buttons.

### step6-pass

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Passed
| description | A mechanism for controlling the audio is provided within the first five links or buttons on the web page.

### step6-fail

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Failed
| description | No mechanism for controlling the audio is provided within the first five links or buttons on the web page.

**Comment by 2biazdk** [comment]
@WilcoFiers Please have a look at the above. (I'm a bit unsure whether the format for the results / user input is outdated?)

**Comment by annethyme** [comment]
Seeking to handle this through new rule for this: #416.
