### ISSUE TITLE
Form field label is descriptive needs context in expectation

### ISSUE THREAD

**Issue by rvantonisse** [auto-wcag/auto-wcag#423]
While using the "Form field label is descriptive" rule to audit certain pages we stumbled onto situations where we would fail the SC because the label alone was not descriptive enough. However when looking at WCAG it is clear that we should not fail the SC because the labels where descriptive enough in context. We think the rule should be updated and that the expectation should explictly mention the fact that labels and their context together are expected to be descriptive of the purpose.

For instance a fieldset or heading above a part of the form can provide additional information about what should be filled in. For example the labels (name and street) below are not enough to determine the purpose of the field, but together with their context (the heading above it) it is enough to determine the context.

## Shipping adress 
Name 
Street
etc.

## Billing adress
Name
Street
etc.

**Comment by annethyme** [comment]
Working on it here: https://github.com/auto-wcag/auto-wcag/pull/447.

I am not sure I completely agree, but let's hear what reviewers say

**Comment by annethyme** [comment]
Closing issue, since there is a pull request for it.
