### ISSUE TITLE
Rule: Form field has accessible name (Discussion)

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#453]
Rule: "Form field has accessible name" (label)
- https://auto-wcag.github.io/auto-wcag/rules/SC4-1-2-form-field-has-name.html

Description:
In the page - https://www.accessibility.nl/wai-tools/validation-test-sites/ns-international/, there is an element as below:

```html
<div class="slick-track" style="opacity: 1; width: 3006px; left: 0px;" role="listbox">
	<!-- ...contents -->
</div>
```

This element has no accessible name, and therefore fails this rule. 
We think the rule should change to only include `implicit` `[role=listbox]` elements.

**Comment by annethyme** [comment]
@jkodu, I don't understand why you would not want to fail this case?

**Comment by jkodu** [comment]
@annethyme - there was a misunderstanding. Closing this as it is not relevant.
