### ISSUE TITLE
Fix SVG test case for "Image has accessible name" rule

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#460]
While working on https://github.com/auto-wcag/auto-wcag/pull/419 we (@Brynanders, @WilcoFiers and I) discovered  that `svg` elements are not in the HTML namespace, and therefore the SVG "inapplicable" test cases for "Image has accessible name" rule, https://auto-wcag.github.io/auto-wcag/rules/SC1-1-1-image-has-name.html, should be changed to say that they are inapplicable because of the namespace. We suggest adding role="img" to the test cases as well.

**Comment by Brynanders** [comment]
### Inapplicable example 1

Element that does not have the semantic role of `img`

``` html
 <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
```

to...

Element is not an HTML element

``` html
 <svg xmlns="http://www.w3.org/2000/svg" role="img" width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
```

**Comment by Brynanders** [comment]
We also propose removing Inapplicable example 4 as its redundant with the above proposed change.

### Inapplicable example 4

Non-image element.

``` html
 <svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
```

**Comment by Brynanders** [comment]
Opened #468
