### ISSUE TITLE
Is SC4-1-1-unique-attrs test 'page' wide or element specific?

### ISSUE THREAD

**Issue by EmmaJP** [auto-wcag/auto-wcag#47]
While I understand that the guideline is element specific, the rule refers to HTML document as a whole as well as the individual elements.

Current rule https://github.com/auto-wcag/auto-wcag/blob/master/_rules/SC4-1-1-unique-attrs.md includes:

...

**Selector**

Select all opening tags in the HTML document

**Step 1**

Make a list of all the attribute names on the current tag

Check if any of the attributes occurs more the once:

Return [step1-fail][#step1-fail]

Else, return [step1-pass][#step1-fail]

...

Fail: "Attribute was used more then once on the element"

**Comment by EmmaJP** [comment]
The test could work for any size block or snippet of HTML code. It doesn't need a full page to load, but can check all the provide code in one sweep. I suggest the following:

...

**Selector**

Select all opening tags in the HTML code.

**Step 1**

For each tag, make a list of all the attribute names on the tag. Do any of the attributes occur more than once in the list?

if yes, return [step1-fail](#step1-fail)

**Step 2**

Confirm there were no fails.

if yes, return [step2-pass](#step2-pass)

...

Fail "Attribute [attribute-name] is used more than once on element [element-pointer]."
Pass "Attributes only occur once per element."

**Comment by WilcoFiers** [comment]
This doesn't need step 2. You can just say:

```
if yes, return step1-fail

Otherwise return step1-pass
```

**Comment by EmmaJP** [comment]
You think this should fail or pass for each element, rather than the whole block being checked?

**Comment by WilcoFiers** [comment]
I don't follow. What 'whole block' do you mean?

**Comment by EmmaJP** [comment]
The selector is "all opening tags in the HTML document". (I've suggested changing document to code, as this test could be done on a code snippet as well as a full document.)

If the HTML has, for example, 20 elements... 
- it will be helpful to identify each element that fails.
- should the test return one pass or 20 pass results?

**Comment by EmmaJP** [comment]
Based on above and further comment on https://github.com/auto-wcag/auto-wcag/issues/46 I guess something like this then:

...

**Selector**

Select all opening tags in the HTML code.

**Step 1**

For each tag, make a list of all the attribute names on the tag. Do any of the attributes occur more than once in the list?

if yes, return [step1-fail](#step1-fail)

else, return [step2-pass](#step2-pass)

...

Fail "Attribute [attribute-name] is used more than once on element [element-pointer]."
Pass "Attributes only occur once on element [element-pointer]."

**Comment by WilcoFiers** [comment]
Looks good. The one thing I think still needs to change is to replace "For each tag" with "For the selected tag".

Unrelated question. Is it useful that at the bottom of every selector we say something like: "For each selected item, go through the following steps". Would that help make the rules clearer?

**Comment by EmmaJP** [comment]
"Select all..." would create some sort of node list, so the test needs to be repeated for each element that has been selected.

I guess a sentence like you suggest would cover that.

**Comment by WilcoFiers** [comment]
Opened a new issue for this question. @EmmaJP  can you create a PR for this rule update and than close this issue?
