### ISSUE TITLE
Add "For each selected item, go through the following steps"

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#51]
Is it useful that at the bottom of every selector we say something like: "For each selected item, go through the following steps". Would that help make the rules clearer?

**Comment by WilcoFiers** [comment]
@gianwild @annethyme Please leave your thoughts below.

**Comment by gianwild** [comment]
Can you please define 'selector'- perhaps provide an example @wilcofiers

**Comment by EmmaJP** [comment]
Sounds good to me. Would definitely clear things up for many of the rules.

**Comment by WilcoFiers** [comment]
@gianwild Auto-WCAG selectors are described here:
https://auto-wcag.github.io/auto-wcag/pages/design/rule-design.html#selector

**Comment by WilcoFiers** [comment]
This issue is resolved with PR #62
