### ISSUE TITLE
Add tests to SC4-1-1-accesskey, SC4-1-1-id and SC4-1-1-unique-attrs

### ISSUE THREAD

**Issue by EmmaJP** [auto-wcag/auto-wcag#58]
Add tests to these 3 draft rules, based on the template created from https://github.com/auto-wcag/auto-wcag/issues/57.

**Comment by WilcoFiers** [comment]
---
rule_id: SC4-1-1-accesskey

success_criterion:
- 4.1.1 # Parsing (Level A)
---

<h2>inapplicable</h2>

<div data-outcome="incomplee">
    <button accesskey="">button</button>
</div>

<h2>step1-pass</h2>

<div data-outcome="passed"
  data-outcome-id="step1-pass">
    <button accesskey="b">button</button>
</div>

<h2>step1-fail</h2>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    
    <button accesskey="A">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    
    <button accesskey="a">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    
    <button accesskey="abcd">button</button>
</div>

**Comment by WilcoFiers** [comment]
```
---
rule_id: SC4-1-1-id

success_criterion:
- 4.1.1 # Parsing (Level A)
---

<h2>inapplicable</h2>

<div data-outcome="incomplee">
    <button>button</button>
</div>

<div data-outcome="incomplee">
    <button id="">button</button>
</div>

<h2>step1-pass</h2>

<div data-outcome="passed"
  data-outcome-id="step1-pass">
    <button id="unique">button</button>
</div>

<div data-outcome="passed"
  data-outcome-id="step1-pass">
    <!-- IDs are case sensitive -->
    <button id="UNIQUE">button</button>
</div>

<h2>step1-fail</h2>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <!-- First -->
    <button id="not-unique">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <!-- Second -->
    <button id="not-unique">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <!-- Third -->
    <button id="not-unique">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <!-- With space, not recommended, but valid -->
    <button id="not unique">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <!-- Second -->
    <button id="not unique">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <!-- Unicode! -->
    <button id="☀😎🌡">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <!-- Second -->
    <button id="☀😎🌡">button</button>
</div>
```

**Comment by WilcoFiers** [comment]
```
---
rule_id: SC4-1-1-unique-attrs

success_criterion:
- 4.1.1 # Parsing (Level A)
---

<h2>inapplicable</h2>

<div data-outcome="incomplee">
    <button>button</button>
</div>

<h2>step1-pass</h2>

<div data-outcome="passed"
  data-outcome-id="step1-pass">
    <button type="submit">button</button>
</div>

<h2>step1-fail</h2>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <button type="submit" type="submit">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <button type="submit" type="reset">button</button>
</div>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <button disabled disabled>button</button>
</div>
```

**Comment by WilcoFiers** [comment]
> Presume each is a complete block of code the test is run against as a whole, with meta-data for comparison on the `<div>` and elements that the test will check inside each `<div>`.
Yep

> Presume data outcome should be "incomplete" with a t ... corrected. Seems OK for an empty attribute but an odd outcome for inapplicable code with no attribute to check.

I'm not sure I understand. Can you clarify?

> Accesskeys ... should inapplicable include <button>button<button>?

Why not? Accesskeys only make sense on an interactive element.

> Also, I think these draft rules might still need #62 applied.

Yes

**Comment by EmmaJP** [comment]
The suggestion for accesskeys is:

<h2>inapplicable</h2>

<div data-outcome="incomplete">
    <button accesskey="">button</button>
</div>

It seems to be missing (compared to the other two code blocks above):

<div data-outcome="incomplete">
    <button>button</button>
</div>

Comparing accesskeys and id ... either accesskeys should include the no-accesskeys scenario, or id should not include it.

**Comment by EmmaJP** [comment]
>      Presume data outcome should be "incomplete" with a t ... corrected. Seems OK for an empty attribute but an odd outcome for inapplicable code with no attribute to check.
> 
> I'm not sure I understand. Can you clarify?

Incomplete was spelt "incomplee" a couple of times, I already edited the comments to correct it.

The word "incomplete" seems an appropriate outcome when something being checked is empty or missing something (eg. id=""). However, it feels incongruous for the situation where a rule does not apply (eg. a set of elements with zero id attributes), where "inapplicable" might suit better.

They may seem similar, but are not quite the same.

**Comment by WilcoFiers** [comment]
Agreed. I'm updating them now. Do you want me to put together a PR?

**Comment by EmmaJP** [comment]
https://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140311/F17 has been dropped from WCAG, so  there no longer needs to be a check for duplicate accesskey values.

https://auto-wcag.github.io/auto-wcag/rules/SC4-1-1-unique-id.html has already been updated.

So only unique attributes needs a rule rewritten.

**Comment by EmmaJP** [comment]
https://github.com/auto-wcag/auto-wcag/pull/256

https://github.com/auto-wcag/auto-wcag/issues/329

https://github.com/auto-wcag/auto-wcag/issues/328
