### ISSUE TITLE
accesskey duplicates

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#59]
Discussion page for the comment by @gianwild here:
https://github.com/auto-wcag/auto-wcag/pull/53

**Comment by WilcoFiers** [comment]
@gianwild Your previous comment referred to not allowing accesskeys for known browser functions such as `ctrl + p` for print and `ctrl + s` for save. Looking at a little more detail, I do not know of any conflicting accesskeys. All of them either go on `alt` for Windows, or `ctrl + alt` for Mac. Because of that I don't think there is any conflict. Can you provide a case where there would be one? If not I think we can skip this comment.

**Comment by gianwild** [comment]
ok

**Comment by WilcoFiers** [comment]
Agreed. I think this issue is resolved.
