### ISSUE TITLE
Update Electron

### ISSUE THREAD

**Issue by EmmaJP** [auto-wcag/auto-wcag#65]
From Github:

"We found a potential security vulnerability in a repository for which you have been granted security alert access.

    **bbc/bbc-a11y**

Known **critical severity** security vulnerability detected in **electron >= 1.7.0,< 1.7.11** defined in package-lock.json. 
package-lock.json update suggested: **electron ~> 1.7.11**. 

_Always verify the validity and compatibility of suggestions with your codebase._"

This is something to check and potentially update dependencies.

**Comment by WilcoFiers** [comment]
Did might be in the wrong repository. Auto-WCAG doesn't use Electron.

**Comment by EmmaJP** [comment]
Sorry, yes, wrong repo
