### ISSUE TITLE
video-description

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#66]
---
rule_id:
name:
test_mode: semi-automatic
environment: Web Browser

success_criterion:
- 1.2.3

authors:
-
---

## Description

Video elements without description track must be reviewed to ensure that audio descriptions aren’t necessary or are provided in a different way.

## Background

- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G78
- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G173
- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/SM6
- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/SM7
- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/FLASH26
- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G203  Understanding documents: 
- https://www.w3.org/TR/UNDERSTANDING-WCAG20/medi[CUT]

## Assumptions

- The video isn't live
- This video contains audio

### Applicability

Any `video` element(s) that does not contain a `track` element with a `kind` attribute set to `descriptions`.

### Expectation

- Either the video does not contain any visual information that is not available through audio; or the information is available as text or audio on the page or through a link on the page.

## Implementation Tests

There are currently no tests available for this rule.

Implementation tests are available at: [rulename tests](rule-id.test.md)

### Version 1.0

- Set up the initial rule

**Comment by WilcoFiers** [comment]
Possible solution to "live" question: If the video has a known duration it can't be live. Similarly, if there is a lost-modified header, the video can't be live.

**Comment by gianwild** [comment]
My comment
“Different way” would need to be specified – perhaps with an example?

Cheers,
Gian

**Comment by WilcoFiers** [comment]
Thinking about this rule a little bit more. I think we might be going about it the wrong way. Firstly, I don't think we can make this a semi-automated rule. Yes, we can check that a video has a track element with a description, but even if it does, it can still be bad. And if it doesn't have one, it can be fine.

I think we should use a rule group here. That's a new idea introduced by ACT. We don't have anything like it in Auto-WCAG, but it actually solves a bunch of problems, most importantly, how do we make sure these different rules map properly to the different success criteria.

Here are my three rules. If a video passes any one of these, it's considered to pass the group as a whole.

- Non-streaming video elements with a description track must have that track be descriptive
  (SC 1.2.3 and 1.2.6)

- Non-streaming video elements or videos embedded through the object element must have all visual information that isn't available through the audio expressed as text available either on the page, or as a link to another page
  (SC 1.2.3 and 1.2.1)

- Non-streaming video elements or videos embedded through the object element must not contain any visual information that is not expressed in the audio
  (SC 1.2.3 and 1.2.6)

**Regarding live video:**
We would define "streaming" as any video that doesn't have a duration that can be determined automatically at the client side without playing the video.

Note that "streaming" isn't the same as "live". You can stream reruns of Frasier, those clearly aren't live. This also means that not every video that should be tested by these success criteria are. But that's not a problem as far as rules go.

**Comment by ShadowBB** [comment]
This Rule group idea sounds like it solves a lot of problems actually. Is this comparable with WCAG stating "use one(!) of the following techniques"?

The more I think about rules the stronger I get the feeling that a rule all in itself can only ever find failures (and then only with the assumption that no alternative is present) and can never pass a SC.

I am unsure how rule groups solve this problem. 

Even if a video element passes the group, this doesn't mean the website or even the page passes the SC, correct?

**Comment by WilcoFiers** [comment]
@ShadowBB Thanks for the feedback. You are absolutely right. The way I like to think of it is that we're taking an SC that usually is somewhat ambiguous, we strip off all the ambiguous parts of it and we break up the remainder into atomic test definitions. So:

1. Passing a rule (or rule group) does not mean the entire page passed the SC - but it does tell you that that particular element does.
2. Failing a rule means that page fails the SC, except if there is a conforming alternative version.

**Comment by EmmaJP** [comment]
Audio description is for blind users - it is an additional narration track that describes things that are visually happening on screen. I guess a media alternative might be a transcript.

**Comment by ShadowBB** [comment]
We have decided to split the above rule into three rules within the same rule group. (See the comments from Wilco from the 9th of Februari).

Here is my drafts for the new rules. Over the course of the coming days I will refine the draft below and once people are happy with it we can replace the original issue with these:

---
rule_id:
name:
test_mode: 
environment: Web Browser

success_criterion:
- 1.2.3

authors:
-
---

## Description

Non-streaming video elements with a description track must have that track be descriptive

## Background

- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G78
- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G173

## Assumptions

- The video isn't live
- This video contains audio

## Test procedure

### Applicability

Any `video` element(s) that contains a `track` element with a `kind` attribute set to `descriptions`.

### Expectation

- The content of the track element describes the visual information that is not available through audio.

## Implementation Tests

There are currently no tests available for this rule.

Implementation tests are available at: [rulename tests](rule-id.test.md)

## Change log

### Version 1.1

- This rule was split from a single rule.

---
rule_id:
name:
test_mode: 
environment: Web Browser

success_criterion:
- 1.2.3

authors:
-
---

## Description

Non-streaming video elements must have all visual information that isn't available through the audio expressed as text available either on the page, or as a link to another page

## Background

- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G78
- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G173

## Assumptions

- The video isn't live
- This video contains audio

## Test procedure

### Applicability

Any `video` element(s).

### Expectation

- Either the text on the same page as the video describes the visual information that is not available through audio or a link on the same page as the video links to a page that contains a text that describes the visual information that is not available through audio.

## Implementation Tests

There are currently no tests available for this rule.

Implementation tests are available at: [rulename tests](rule-id.test.md)

## Change log

### Version 1.1

- This rule was split from a single rule.

---
rule_id:
name:
test_mode: 
environment: Web Browser

success_criterion:
- 1.2.3

authors:
-
---

## Description

Non-streaming video elements or videos embedded through the object element must not contain any visual information that is not expressed in the audio

## Background

- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G78
- https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G173

## Assumptions

- The video isn't live
- This video contains audio

## Test procedure

### Applicability

Any `video` element(s).

### Expectation

- There is no visual information that is not available through audio.

## Implementation Tests

There are currently no tests available for this rule.

Implementation tests are available at: [rulename tests](rule-id.test.md)

## Change log

### Version 1.1

- This rule was split from a single rule.

**Comment by WilcoFiers** [comment]
Closing as this is replaced by #82, #83, #88.
