### ISSUE TITLE
SC2-4-6-descriptive-headings

### ISSUE THREAD

**Issue by geirsf** [auto-wcag/auto-wcag#70]
---
name: Descriptive headings
description: |
This rule checks that headings describe the topic or purpose of the content.

success_criterion: 
- 2.4.6 # Headings and labels

test aspects:
- DOM Tree

authors:
- Dagfinn Rømen
- Geir Sindre Fossøy
- Carlos Duarte
---

### Applicability

The rule applies to any element with the the [semantic role](#semantic-role) of `heading`.

**Note**: The WCAG 2.0 success criterion 2.4.6 applies to all headings.

**Note**: Heading content defines the header of a section (whether explicitly marked up using sectioning content elements, or implied by the heading content itself).

### Expectation

Each target element describes the topic or purpose of the subsequent content.

**Note**: Headings do not need to be lengthy. A word, or even a single character, may suffice.

## Assumptions

- Heading markup is covered by success criterion 1.3.1 Info and Relationships.

## Accessibility Support

There are no major accessibility support issues known for this rule.

## Background

- https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html
- https://www.w3.org/TR/WCAG20-TECHS/G130.html
- https://www.w3.org/TR/WCAG20-TECHS/H42.html
- https://www.w3.org/TR/WCAG20-TECHS/ARIA12.html
- https://www.w3.org/TR/html52/dom.html#heading-content

### Passed

```html
<!-- Heading marked up with h-element that describes the topic or purpose of the following section of content -->
<h1 class="target">Opening Hours</h1>
<p>We are open Monday through Friday from 10 to 16</p>
```

```html
<!-- Heading marked up with role="heading" that describes the topic or purpose of the following section of content -->
<span role="heading">Opening Hours</span>
<p>We are open Monday through Friday from 10 to 16</p>
```

```html
<!-- Heading marked up with h-element with an image that describes the topic or purpose of the following section of content -->
<h1 class="target"><img scr="../test-assets/opening_hours_icon.png" alt="Opening hours"></img></h1>
<p>We are open Monday through Friday from 10 to 16</p>
```

```html
<!-- Heading marked up with h-element that is a single character that describes the topic or purpose of the following section of content -->
<h1 class="target">A</h1>
<dl>  
<dt>airplane</dt>
  <dd>a powered flying vehicle with fixed wings and a weight greater than that of the air it displaces.</dd>
 <dt>apple</dt>
  <dd>the round fruit of a tree of the rose family, which typically has thin green or red skin and crisp flesh.</dd>
</dl>
```

### Failed

```html
<!-- Heading marked up with h-element that does not describe the topic or purpose of the following section of content -->
<h1 class="target">Weather</h1>
<p>We are open Monday through Friday from 10 to 16</p>
```

```html
<!-- Heading marked up with role="heading" that does not describe the topic or purpose of the following section of content -->
<span role="heading">Weather</span>
<p>We are open Monday through Friday from 10 to 16</p>
```

### Inapplicable

```html
<!-- No heading -->
<p>We are open Monday through Friday from 10 to 16</p>
```

```html
<!-- Heading that is not visible to users -->
<h1 style="display: none;">Opening hours</h1>
<p>We are open Monday through Friday from 10 to 16</p>
```

**Comment by WilcoFiers** [comment]
> All headings that can be identified by bolder text, the text being italic, or larger font-size.

Are you saying here that every text that has one of these properties should be considered a heading? If so, I'm not sure that's true. It also begs the question, larger / bolder than what?

**Comment by DagfinnRomen** [comment]
Agree, we need more specific information on what is considered a heading. We have reused the assumption from an existing draft, https://github.com/auto-wcag/auto-wcag/blob/master/_drafts/SC1-3-1-p-as-heading.md

**Comment by EmmaJP** [comment]
This should also include all content marked as a heading element.

Determining what other text could be considered a heading is a lot less clear cut and can easily include things not intended to be a heading. I suspect that would need a person to determine.

**Comment by geirsf** [comment]
Made some changes in the Applicability and Assumptions for the testrule.

**Comment by DagfinnRomen** [comment]
Added test cases.

**Comment by ShadowBB** [comment]
After the meeting today we changed the applicability to not test for the definition of headers, we will leave that up to a different rule. (possibly in 1.3.1 or in a rule group with this rule).

We added assumptions that reflect this and also restructured the test cases to reflect this.

We also added an aria and image test case.

**Comment by ShadowBB** [comment]
We might need to include "that is [visible on the page][] or [exposed to assistive technologies][]" in the applicability, and if we include that we need to add some additional test cases.
