### ISSUE TITLE
Chore: Improve test cases format

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#72]
The current format looks like this:

```md
---
rule_id: SCx-y-z-name

success_criterion:
- x.y.z
---

<h2>inapplicable</h2>

<div data-outcome="incomplete">
    <!-- HTML code here -->
</div>

<!-- other incomplete examples if needed -->

<h2>step1-pass</h2>

<div data-outcome="passed"
  data-outcome-id="step1-pass">
    <!-- HTML code here -->
</div>

<!-- more test cases -->

<h2>step1-fail</h2>

<div data-outcome="failed"
  data-outcome-id="step1-fail">
    <!-- HTML code here -->
</div>

<!-- more test cases -->

<h2>step#-pass/fail</h2>

<!-- Add pass / fail / incomplete examples for every step that has them -->
```

There are a number of limitations to this: 
- This format is fairly verbose
- It doesn't allow us to isolate tests from one another
- The metadata could actually impact the test

The ACT TF has developed an alternative format, which comes with its own advantages and disadvantages. We should think about what would be the easiest format for us to work with. 
https://github.com/w3c/wcag-act-rules/blob/master/_rule-tests/ACT-R1-tests.html

**Comment by EmmaJP** [comment]
Could we use Markdown with HTML code snippets?

I think it is important that any HTML code snippets look like HTML would look in your code editor.
I don't think the test case files need to be something that drops into a tool that sanity checks the test tool.

**Comment by WilcoFiers** [comment]
Capturing some meeting discussions:

The markdown + code snippets format used here seems like a good way forward
https://github.com/auto-wcag/auto-wcag/issues/73

One addition to it would be ti include metadata about if the test cases should be part of a template or not. That template should be created so that this can be tested consistently.

**Comment by WilcoFiers** [comment]
@kensgists @EmmaJP @jkodu 

How about the following:

````md
---
rule_id: SCx-y-z-name
template: default
success_criterion:
- x.y.z
---

## Passed

```html
<img src="moon.jpg" alt="Moon" />
```

```html
<!-- Use class="target" to indicate the test target if there are multiple elements -->
<img src="moon.jpg" aria-labelledby="moon" class="target" />
<div id="img-desc">Moon</div>
```

... other passed examples if needed

## Failed

```html
<!-- HTML code here -->
```

... other failed examples if needed

## Inapplicable

```html
<!-- HTML code here -->
```

... other incomplete examples if needed

````

**Comment by jkodu** [comment]
Believe, the test cases are written in this format, for all the published rules and the ones being worked upon. Closing.
