### ISSUE TITLE
SC2-1-2-no-keyboard-trap-r1 - Test-case

### ISSUE THREAD

**Issue by geirsf** [auto-wcag/auto-wcag#73]
---
rule_id: SC2-1-2-no-keyboard-trap-r1
test_case_template: default
success_criterion: 
- 2.1.2  No Keyboard Trap (level A)
---

## Passed
```
<a href ="#">Link 1</a>
<button class="target">Button1</button>
```

## Failed
```
<a href="#">Link 1</a>
<button class="target" onblur="setTimeout(() => this.focus(), 10)">Button1</button>
```
```
<button class="target" onblur="setTimeout(() => this.nextSibling.focus(), 10)">Button1</button>
<button class="target" onblur="setTimeout(() => this.previousSibling.focus(), 10)">Button2</button>
```
## Inapplicable
```
<h1>Page 1</h1>
```

**Comment by WilcoFiers** [comment]
The tests should probably indicate which element has the failure. I would propose adding `class="target"` to the element that failed. WDYT?

**Comment by MaliinO** [comment]
We agree and have updated the proposal.
