### ISSUE TITLE
SC3-1-1-xml-lang --draft

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#74]
---
name: SC3-1-1-xml-lang
group: # (what goes here?)
description: |
  This rule checks the value of the `xml:lang` and/or the `lang` attribute.

success_criterion:
- 3.1.1

test_aspects:
To run the test cases, the below conditions are necessary.
1. DOM Tree: The tree that HTML is parsed into.
2. Accessibility Tree: The tree that user agents expose to the accessibility API.
3. HTTP Messages: All messages sent through HTTP(s)

authors:
- Jey [<jey.nandakumar@deque.com>]
---

## Test Procedure (1)
For `html` element.
1. Examine the `html` element of the document.
2. Check that the `html` element has a `lang` and or `xml:lang` attribute.
3. Check that the value confirms to [BCP 47](https://www.ietf.org/rfc/bcp/bcp47.txt).

### Expectation (1)
- The above checks are all true.

## Test Procedure (2)
For `object` embedded element.
1. Examine the `object` element of the document.
2. Check that the `object` element has a `lang` and or `xml:lang` attribute.
3. Check that the value confirms to [BCP 47](https://www.ietf.org/rfc/bcp/bcp47.txt).

### Expectation (2)
- The above checks are all true.

## Test Procedure (3)
Checking language in HTTP(S) Request Headers & Responses.
1. Examine the `request` and `response` from a XHR.
2. Check that a `request` has passed `Accept-Lanauage` in the header to advertise which languages that the client is able to undersand.
2. Check that the `response` stream and  `Content-Language` response header is specified.
3. Check that the value confirms to [BCP 47](https://www.ietf.org/rfc/bcp/bcp47.txt).

### Expectation (3)
- The above checks are all true.

### Applicability
This rule applies to the `html`, `object`, `xhr request` & `xhr response`.

## Assumptions
Past tests have shown that `xml:lang` is ignored by certain screenreaders (Both Jaws 15 with FF and IE, as well as NVDA with FF). This test identifies pages that use only the `xml lang` attribute.

## Accessibility support
There are no major accessibility support issues known for this rule.

## Background
The `xml:lang attribute` is a universal attribute to mark up and or specify the human language that an element contains, confirming to the XML 1.0 documents. It is synonymous to the `lang` attribute and can/ should be used in parallel to allow for back-ward compatability.

Further References:
- https://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140408/H57
- https://www.ietf.org/rfc/bcp/bcp47.txt
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:lang
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
- https://www.w3.org/WAI/WCAG20/quickref/?showtechniques=311#qr-meaning-doc-lang-id

**Comment by jribbens** [comment]
I'm a bit confused as to what this rule is testing.

* Where does the idea come from that the `lang` attribute is mandatory for <object> elements?
* What does "examine the request from a XHR" mean? What XMLHttpRequest is it talking about?
* Where does the idea come from that `Accept-Language` is mandatory for XMLHttpRequests, and that `Content-Language` is mandatory in HTTP replies to them?
* The Assumptions section appears to be more a description of the rule, and an inaccurate one at that (none of the tests identify pages that use only the `xml lang` attribute).

I'd suggest the following checks for Test Procedure (1):

* Examine the `html` element of the document.
* Check that the values of each of the `lang` and `xml:lang` attributes, if present, conform to BCP 47.
* If both the `lang` and `xml:lang` attributes are present, check their values are identical when compared case-insensitively.
* If this is an XHTML document, check that at least one of the `lang` and xml:lang` attributes are present.
* If this is an HTML document, check that the `lang` attribute is present.

If screenreaders don't find the `xml:lang` attribute even in XHTML documents then it might be better to change the penultimate rule to check that both attributes are present.

**Comment by WilcoFiers** [comment]
I would propose we do the following. I'm not sure if we need to keep the object and XML requests around. I think that's a separate discussion. Maybe create 3 issues, one for each of these rules?

## SC3-1-1-html-has-lang

### Applicability

The root node of the page, if it is an `<html>` element.

### Expectations

1. The element has a `lang` or `xml:lang` attribute

---

## SC3-1-1-html-lang-valid

### Applicability

The root node of the page, if it is an `<html>` element with a `lang` and/or `xml:lang` attribute.

### Expectations

1. The value of the `lang` and/or `xml:lang` attribute conforms to [BCP47](https://www.ietf.org/rfc/bcp/bcp47.txt)

---

## SC3-1-1-html-xml-lang-match

### Applicability

The root node of the page, if it is an `<html>` element with both `lang` and `xml:lang` attributes.

### Expectations

1. The value of the `lang` and `xml:lang` attributes are the same

**Comment by jkodu** [comment]
@jribbens 
Thanks for the notes, I will update accordingly.
You are right. The XHR is an advisory tecnique as listed here, but is not mandatory.
Reference: https://www.w3.org/WAI/WCAG20/quickref/?showtechniques=311#qr-meaning-doc-lang-id

@WilcoFiers 
Sure, that would make sense, to seperate the rules to 3 different ones.

**Comment by jribbens** [comment]
I'd just add to @WilcoFiers' suggestion that there also needs to be a rule that, iff this is an HTML (as opposed to XHTML) document then `lang` is mandatory - `xml:lang` alone is not acceptable.

**Comment by jkodu** [comment]
@WilcoFiers 
As advised, have created three issues.
https://github.com/auto-wcag/auto-wcag/issues/75
https://github.com/auto-wcag/auto-wcag/issues/76
https://github.com/auto-wcag/auto-wcag/issues/77

Closing this issue.

@jribbens - Thanks for your comments.
