### ISSUE TITLE
SC3-1-2-text (draft)/ parked for now

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#79]
---
name: SC3-1-2-text

description:
- This rule checks for any changes in the human language, with in the contents of a web page & ensures if they are marked up correctly with the relevant `lang` attribute for any such changes.

success_criterion:
- 3.1.2

test_aspects:
- DOM Tree: The tree that HTML is parsed into.

authors:
- Jey Nandakumar
---

### Applicability

- Any valid DOM node/ element.
- The test is applied to natural language test, and is not applicable to content of `script` elements, attribute and comments.

### Expectation

- The element has a `lang` attribute & that the value conforms to [BCP 47](https://www.ietf.org/rfc/bcp/bcp47.txt).
- The element is visible.
- The test applies to visible text as contents of the element, and not to text in attributes of the element.
- The language (identified using a language assertion algorithm) used in the text matches specified in the attribute.

## Assumptions

*There are currently no assumptions*

## Accessibility support

This rule is only applicable in a scenario where assistive technologies are inconsistent about how they determine the language of the page.

## Background

- https://www.ietf.org/rfc/bcp/bcp47.txt
- http://wiki.egovmon.no/wiki/SC3.1.2#Element_self::text.28.29
- https://www.w3.org/TR/1999/REC-html401-19991224/struct/dirlang.html#h-8.1.2

### Steps
- Select consecutive run of text of the DOM element to which a `lang` attribute applies. 
- Note: Refer [SC3-1-1-lang](https://github.com/auto-wcag/auto-wcag/issues/78) on how to retrieve relevant DOM element.
- Ensure the element and the text contents, satisfy above expectations.

### Passes
```
<article>
To say good morning in Dutch, you would say <p lang="nl">Goedemorgen</p>
</article>
```

### Failed

```html
<article lang="en">
Goedemorgen
</article>
```

### Inapplicable

```html
<article>
<!--
<p lang="nl">Goedemorgen</p>
-->
Good Morning
</article>
```

**Comment by jribbens** [comment]
Presumably this *should* apply to some attributes, e.g. `alt` and `aria-label` (I wonder if `<div lang="en"><img alt="Bonjour" lang="fr">` is correct...). I'm not sure if "language assertion algorithm" needs to be elaborated on further but clearly there are going to be both false positives and false negatives, this should probably be noted (is there a systematic way to do this for rules?)

**Comment by WilcoFiers** [comment]
I don't quite understand what you're trying to do with this one. I think we need a separate rule that checks that lang / xml:lang meets BCP 47. That shouldn't be part of this rule I think.

**Comment by jkodu** [comment]
This is parked after previous conversations.
@WilcoFiers - leave it with you to get more direction/ involvement.

**Comment by jkodu** [comment]
@WilcoFiers 
In your plate to get more consensus on this one.

**Comment by jkodu** [comment]
Not relevant. Can open if re-visited.
