### ISSUE TITLE
SC4.1.1-unique-element-id-attributes

### ISSUE THREAD

**Issue by Brynanders** [auto-wcag/auto-wcag#90]
---
name: unique element id attributes
description: |
  This rule checks that all `id` attribute values on a single page are unique.

success_criterion:
- 4.1.1 # Success Criterion 4.1.1 (Parsing)

test_aspects:
- DOM Tree

authors:
- Bryn Anderson
- Jey Nandakumar
---

### Applicability

Any element with an `id` attribute.

### Expectation

All `id` attribute values are unique.

## Assumptions

There are currently no assumptions.

## Accessibility Support

There are no major accessibility support issues known for this rule.

## Background
- https://www.w3.org/WAI/WCAG20/quickref/?showtechniques=411#qr-ensure-compat-parses
- https://www.w3.org/TR/WCAG20-TECHS/H74.html
- https://www.w3.org/TR/WCAG20-TECHS/H93.html
- https://www.w3.org/TR/WCAG20-TECHS/H94.html

### Passed

```html
<div id="my-div"> This is my first element</div>
```

```html
<div id="my-div1"> This is my first element</div>
<div id="my-div2"> This is my second element</div>
<svg id="my-div3"> This is my third element</svg>
```

```html
<div id="my-elm"></div>
<script>
  var myElm = document.getElementById('my-elm');
  var shadow = myElm.attachShadow({ move: 'open' });
  shadow.innerHTML = '<b id="my-elm"><slot /></b>';
</script>
```

### Failed

```html
<div id="my-div"> This is my first element</div>
<div id="my-div"> This is my second element</svg>
```

```html
<div id="my-div"> This is my first element</div>
<svg id="my-div"> This is my second element</svg>
```

### Inapplicable

```html
<div>This is my first element</div>
```

```html
<div xml:id="my-div">This is my first element</div>
```

**Comment by Brynanders** [comment]
Should this check be part of a group? It looks to be conditional along with H74 and H94 under eth Sufficient Techniques for 4.1.1 https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/ensure-compat-parses.html

**Comment by WilcoFiers** [comment]
Nope, this doesn't have to be in a group. This rule should not flag elements in different trees with the same ID. I'm not sure how xml:id and id relates to this, or what happens if you use shared IDs between different technologies, HTML and SVG IDs should have different name spaces, so those may not be a problem either.

**Comment by Brynanders** [comment]
I updated Applicability to include "...on a single page...".
